### ISSUE TITLE
Version and build information missing in 2.3.0 binaries attached to the release

### ISSUE THREAD

**Issue by sirnewton01** [grafana/loki#4174] opened 2021-08-16 18:43 UTC
**Describe the bug**
When downloading the binaries for the latest 2.3.0 release many of them for both loki and promtail appear to have no version information. So far, i'm seeing this with promtail on darwin-amd64/linux-amd64 and also loki for linux-amd64.

**To Reproduce**
1. Run either loki-xyz --version or promtail-xyz --version

**Expected behavior**
It is expected as in previous releases that version, build date, and build user information are shown.

Instead, the output looks something like this:
```
promtail, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.16.2
  platform:         linux/amd64
```

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: manual deployment

**Screenshots, Promtail config, or terminal output**

**Comment by dannykopping** [comment] 2021-08-16 21:42
Thank you for reporting @sirnewton01 :+1: 
Closing is a duplicate of #4170

**Closed by dannykopping** 2021-08-16 21:42 UTC
