### ISSUE TITLE
docker plugin loki cause docker run block

### ISSUE THREAD

**Issue by yuanyongjun** [grafana/loki#5689] opened 2022-03-22 02:21 UTC
docker Server Version: 20.10.6
docker-compose version 1.29.1
daemon.json:
`{
 "graph":"/var/docker/lib",
    "debug" : true,
    "log-driver": "loki",
    "log-opts": {
        "loki-url": "http://localhost/loki/api/v1/push",
        "loki-batch-size": "400"
    }
}
`

i get offline loki plugin package to server ,and unzip package to the docker install directory,modify the daemon.jon,last restart docker.
but when i start many service docker container by tool docker-compose ,it's blocking.End i ctrl+c to exit.how it's cause?

**Comment by jeschkies** [comment] 2022-03-22 13:38
Seems this is a duplicate of https://github.com/grafana/loki/issues/2361. Please also see the [know issue](https://grafana.com/docs/loki/latest/clients/docker-driver/#know-issues) section in the documentation. Does this help a little?

**Comment by dannykopping** [comment] 2022-03-22 16:11
Agreed that this seems like a duplicate. Closing the issue.

**Closed by dannykopping** 2022-03-22 16:11 UTC
