### ISSUE TITLE
promtail process keeps a deleted file open and deleted file will occupy space on disk

### ISSUE THREAD

**Issue by yaserdashti** [grafana/loki#3914] opened 2021-06-30 05:13 UTC
**Describe the bug**
(actual log names changed)
we noticed space issues on some servers and after digging a bit find out the deleted log files are kept opened by promtail and the only way to free up the space is restarting the promtail

- job_name: jobname1
    static_configs:     
    - targets:     
        - localhost
      labels:      
        job: job1
        __path__: /var/log/app1/app1*.log

 lsof|grep deleted  
promtail  24618            promtail   49r      REG              253,4 58580600179     132710 /var/log/app1/app1.log-20210628 (deleted)
promtail  24618 12088      promtail   49r      REG              253,4 58580600179     132710 /var/log/app1/app1.log-20210628 (deleted)
promtail  24618 24639      promtail   49r      REG              253,4 58580600179     132710 /var/log/app1/app1.log-20210628 (deleted)
promtail  24618 24640      promtail   49r      REG              253,4 58580600179     132710 /var/log/app1/app1.log-20210628 (deleted) 

apart from application log, i can see the same behaviour on OS journal logs:
promtail   65907  67660      promtail   13r      REG              253,4    16777216     655454 /var/log/journal/a7d6bbf65bfa4766b8f6e3ef7ee62afe/system@ff981cf568ef46659a8d540f55f1c785-0000000003b5841a-0005c53babde6297.journal (deleted)
promtail   65907  67660      promtail   14r      REG              253,4    52428800     655659 /var/log/journal/a7d6bbf65bfa4766b8f6e3ef7ee62afe/user-1000@37fb3491b2cd42a3bb0a408927e33126-0000000003b9108e-0005c5555fadaf05.journal (deleted)
promtail   65907  67660      promtail   15r      REG              253,4     8388608     656132 /var/log/journal/a7d6bbf65bfa4766b8f6e3ef7ee62afe/user-501896@c482929c739f4714ae48d6c3d459c032-0000000000000000-0000000000000000.journal (deleted)
promtail   65907  67660      promtail   16r      REG              253,4     8388608     656153 /var/log/journal/a7d6bbf65bfa4766b8f6e3ef7ee62afe/user-501217@cc4f3a308e9a4fa1ad184501d94d8102-0000000000000000-0000000000000000.journal (deleted)
promtail   65907  67660      promtail   17r      REG              253,4    52428800     655470 /var/log/journal/a7d6bbf65bfa4766b8f6e3ef7ee62afe/user-1000@37fb3491b2cd42a3bb0a408927e33126-0000000003b7e3f4-0005c54cd923defe.journal (deleted)

**To Reproduce**
1. Started Loki (SHA or version) promtail version 2.2 b6f001f3120c061ece46d87250275b5f  promtail-linux-amd64 
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

when the file is deleted, (due to log rotation or log clean up), promtail should release the file and let it go!! (not keeping it open and occupy disk space)

**Environment:**
  - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]  baremetal (dell server) Ubuntu 18.04 kernel  4.15.0-20
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by yaserdashti** [comment] 2021-08-28 03:48
@SoftDed unfortunately I didn't get any response on this case. I've just scheduled a routine promtail restarts on affected hosts to workaround the issue for now.

**Comment by darxriggs** [comment] 2023-03-24 14:14
@rfratto @dannykopping Do you or a colleague have any feedback on this topic?
Is promtail holding file handles for deleted files (`file` and `journal` target) forever?

**Comment by dannykopping** [comment] 2023-03-24 14:53
I don't have any insight into this off-hand, but yes I could see how an open file handle would prevent the underlying contents from being unlinked.

I will reopen.

**Comment by darxriggs** [comment] 2023-04-09 21:17
The journal part should be fixed in #8987.

**Comment by darxriggs** [comment] 2023-04-10 20:40
I tried to reproduce the reported issue with the `file` target.

Result: In my manual tests with promtail v2.8.0, the file descriptors for a) deleted and b) moved files are correctly released.

Used configuration:
```
scrape_configs:
  - job_name: log files
    static_configs:
      - labels:
          __path__: /tmp/test*.log
```

**Comment by cstyan** [comment] 2023-11-08 01:38
closing since it sounds like it has been fixed, please comment if you have a case that results in the same issue

**Closed by cstyan** 2023-11-08 01:38 UTC
Labels: keepalive, component/promtail
