### ISSUE TITLE
Bug: Latest helm-loki release (6.7.2) not installable.

### ISSUE THREAD

**Issue by Tommyf** [grafana/loki#13633] opened 2024-07-23 22:32 UTC
The latest release of the loki helm chart ([helm-loki-6.7.2](https://github.com/grafana/helm-charts/releases/tag/helm-loki-6.7.2)) is not usable as it is too large.

As this is a 'patch' level version bump, many environments will automatically pick up this new version (as it's meant to be a non-breaking change) and then failure will occur.

**Steps to reproduce the behavior**
Use Helm to install or update Loki using version 6.7.2 of the Helm Chart:
`helm install releasename -f myvalues.yaml --version 6.7.2 grafana/loki `
or
`helm update releasename -f myvalues.yaml --version 6.7.2 grafana/loki `

The above results in the following error as the Helm Chart is too big to fit inside a Kubernetes Secret:
`Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728`

**Expected behavior**
The command should complete without error.

**Cause of behaviour**
Upon investigation, I see that a large binary file has been added to the Helm Chart in commit [bd1d6a7a](https://github.com/grafana/loki/commit/bd1d6a7a35e72a88de318d92c3f994194469d039).
This looks like it was causing tests to fail and was mentioned in #13461.
It seems that the changes were then merged despite the failing test.

This large file will be the reason for the tests failing in that PR.
I see no indication in the commit as to why the file was added, so maybe it was a mistake? Removing it should fix the failing tests and also make the Helm Chart usable again :)

**Comment by fculpo** [comment] 2024-07-24 07:24
Yes, same here

**Comment by jensens** [comment] 2024-07-24 11:21
I can confirm this too.

**Comment by toalba** [comment] 2024-07-24 11:31
Encountered the same issue.

**Comment by stefcho034** [comment] 2024-07-24 12:08
Same here...

**Comment by QuentinBisson** [comment] 2024-07-24 14:10
@Jayclifford345 maybe you can help on this one?

**Comment by bpedersen2** [comment] 2024-07-24 14:52
Also encountered this problem in a SuSE-rancher based installation. 

Fix: cut down the values yaml (in my case: delete minio and enterprise configs) to keep the values.yml < 32kBytes.

Note: per default rancher  passes the full values.yaml from the  chart , but you actually would need only the things that deviate from the default.

**Comment by brainfair** [comment] 2024-07-24 15:02
@bpedersen2 there is nothing to deal with values, the core issue is with helm-test 13mb binary inside src/helm-test directory due to which the size of the chart becomes larger than what is allowed for keeping a helm release secret

possible fix:
- remove helm-test binary
- add helm-test directory or binary to helmignore

**Comment by elchenberg** [comment] 2024-07-24 15:07
I guess the helm-test binary was added to the repository by @Jayclifford345 @JStickler by accident: https://github.com/grafana/loki/commit/bd1d6a7a35e72a88de318d92c3f994194469d039

**Comment by bpedersen2** [comment] 2024-07-24 15:17
> @bpedersen2 there is nothing to deal with values, the core issue is with helm-test 13mb binary inside src/helm-test directory due to which the size of the chart becomes larger than what is allowed for keeping a helm release secret
> 
> possible fixes:
> 
> * remove helm-test binary
> * add helm-test directory or binary to helmignore

But why does then just trimming down the values.yml help in a successful install?

**Comment by Jayclifford345** [comment] 2024-07-24 16:04
Thank you for pointing this out all just working with the Loki team to sort this out. My apologies for causing this issue with my last PR

**Comment by Jayclifford345** [comment] 2024-07-24 16:34
Just waiting for the last of the tests to pass and will get this merged: https://github.com/grafana/loki/pull/13651

**Comment by Jayclifford345** [comment] 2024-07-24 18:23
That is the hotfix merged and should be now fixed. Let me know if you are still running into issues

**Comment by Tommyf** [comment] 2024-07-25 13:55
Release [6.7.3](https://github.com/grafana/helm-charts/releases/tag/helm-loki-6.7.3) looks good!

Thanks for addressing this so quickly! It was not a huge blocker as one could easily pin to a known good version (as you really should be doing anyway), but many people do use unpinned latest releases so this kind of thing catches them (me!) out :)

**Comment by kosmoz** [comment] 2024-07-25 14:16
I can confirm that 6.7.3 works!

**Comment by JStickler** [comment] 2024-07-25 14:57
@Tommyf so can we close this issue?

**Closed** 2024-07-26 08:06 UTC
