### ISSUE TITLE
Support CRIO log format

### ISSUE THREAD

**Issue by jcantrill** [grafana/loki#262] opened 2019-01-31 13:58 UTC
Promtail is capable of reading the CRIO format via raw bytes terminated with new line.  This issue requests supporting an EntryParser that explicitly supports CRIO by reassembling partial lines.  The 'kubectl logs' command already does this [1].  Fluentd concat plugin allows this [2].

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go#L270
[2] https://github.com/fluent-plugins-nursery/fluent-plugin-concat/blob/master/lib/fluent/plugin/filter_concat.rb

**Comment by jcantrill** [comment] 2019-01-31 13:59
cc @brancz

**Comment by tomwilkie** [comment] 2019-01-31 15:31
Thanks for the pointers @jcantril!  I think this is a dupe of #231.  We'd very much welcome any contributions to make this work...

**Closed by tomwilkie** 2019-01-31 15:31 UTC

**Comment by jcantrill** [comment] 2019-02-01 08:17
@tomwilkie It's not quite the same though maybe we should still close the issue in favor of #231.  I would say @portante proposal relies on alternate CRI-O implementation that doesn't exist yet instead of being able to parse CRI-Os format as it exists today.  @brancz and I further discussed this issue and we are considering that it may make more sense to grab logs in their raw form and rebuild them later as needed, which is half of @portante suggestion
