### ISSUE TITLE
Loki arm local binary not starting with the latest loki-local-config.yaml

### ISSUE THREAD

**Issue by ArchBobby** [grafana/loki#3055] opened 2020-12-07 22:50 UTC
**Describe the bug**
Installed Loki following the instructions on the getting started docs. When starting I got the following error:
`Dec 07 22:33:13 ubuntu loki-linux-arm[2020]: failed parsing config: loki-config.yaml: yaml: unmarshal errors:
Dec 07 22:33:13 ubuntu loki-linux-arm[2020]:   line 7: field wal not found in type ingester.Config`

**To Reproduce**
1. Downloaded the config file as in the "Get started" doc
2. Started loki with the provided comman
3. Start up failed

**Expected behavior**
Loki should have started with no erros

**Environment:**
 - Infrastructure: Raspberry Pi 4 8GB
 - Deployment tool: Local binary

**Screenshots, Promtail config, or terminal output**
Logs as prided as above from journalclt:
`Dec 07 22:33:13 ubuntu loki-linux-arm[2020]: failed parsing config: loki-config.yaml: yaml: unmarshal errors:
Dec 07 22:33:13 ubuntu loki-linux-arm[2020]:   line 7: field wal not found in type ingester.Config`

**Note**
I was able to start up Loki after gettting the previous version of the loki-local-config.yaml from git:
https://github.com/grafana/loki/blob/af6e8cb6c9a02be44a978c4933fb17778cb401b7/cmd/loki/loki-local-config.yaml

From the logs and the changes from that file i think the problem is the added config from the master branch here:
`ingester:
  wal:
    enabled: true
    dir: /tmp/wal
    recover: true` 

Thanks all, pretty new to this so cant help more but raise this. :)

**Comment by doodlemania2** [comment] 2020-12-10 19:29
+1 on amd64

**Comment by mikeydecker** [comment] 2020-12-11 20:50
+1 on AMD64

**Comment by kavirajk** [comment] 2020-12-12 15:49
I think the issue is not with any specific architecture but with docs points to config on master branch not the released version.

I think we should version our docs (or at least something like `latest` tag that always points at latest released version).

Anyway we should avoid pointing to master branch's config.

**Comment by go-xmyang** [comment] 2020-12-22 03:28
+1 on AMD64

**Comment by mindthevirt** [comment] 2020-12-23 20:05
@kavirajk is correct. the master version of the file isn't compatible with the released 2.0 Loki version. instead it should point to this file: https://raw.githubusercontent.com/grafana/loki/af6e8cb6c9a02be44a978c4933fb17778cb401b7/cmd/loki/loki-local-config.yaml

**Comment by ArchBobby** [comment] 2020-12-23 20:24
@mindthevirt @kavirajk what should we do here then? Update/rollback the master branch local config?

**Comment by kavirajk** [comment] 2020-12-23 20:29
@ArchBobby for the temporary workaround, you could use the same config from v2.0 branch! 
We already tracking the versioning of docs in another issue. 
https://github.com/grafana/loki/issues/3028

Hopefully Loki docs will be versioned soon! and we won't have this issue

**Comment by bygui86** [comment] 2021-01-06 20:18
[Configuration page](https://grafana.com/docs/loki/latest/configuration/) is out of sync in respect to [WAL page](https://grafana.com/docs/loki/latest/operations/storage/wal/).
Please remember to update that as well once WAL will be GA.

**Comment by kavirajk** [comment] 2021-01-29 11:54
Now loki docs are versioned. Now you can see docs only specific to versions
https://grafana.com/docs/loki/v2.1.0/

Hope this avoids confusion on using configs and docs that are not yet available in the released version of Loki

https://github.com/grafana/website/pull/3312

Closing this!

**Closed by kavirajk** 2021-01-29 11:54 UTC

**Comment by svdmitrij** [comment] 2021-02-01 14:16
Hi! Links on page https://grafana.com/docs/loki/latest/installation/local/ still point at master branch.
```
wget https://raw.githubusercontent.com/grafana/loki/master/cmd/loki/loki-local-config.yaml
wget https://raw.githubusercontent.com/grafana/loki/master/cmd/promtail/promtail-local-config.yaml
```

**Comment by kavirajk** [comment] 2021-02-01 14:31
@svdmitrij that's right. 
latest -> always master

You choose particular version if you want specific version of docs!

**Comment by svdmitrij** [comment] 2021-02-01 15:52
> @svdmitrij that's right.
> latest -> always master
> 
> You choose particular version if you want specific version of docs!

Thank you! Unfortunately not working for me - 
![изображение](https://user-images.githubusercontent.com/1698146/106482602-0c25b780-64c7-11eb-85da-a9b1a9188384.png)

**Comment by kavirajk** [comment] 2021-02-03 08:27
@svdmitrij Thanks for catching that. Now its fixed for all the github links as well.

**Comment by paynege** [comment] 2021-02-05 14:33
the url in this link is not fixed, https://grafana.com/docs/loki/latest/installation/local/

**Comment by LauJangit** [comment] 2021-03-06 08:05
the offical helm chart on artifacthub.io is still not fixed yet
