### ISSUE TITLE
Unable to stream log with high limit, no option to disable limit

### ISSUE THREAD

**Issue by atombender** [grafana/loki#1625] opened 2020-02-03 23:57 UTC
**Describe the bug**
The API seems to have a default limit, and also an upper limit which is undocumented, or even discernible. Here are some example API requests (query doesn't matter):

```
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=110000' | head -n1
HTTP/1.1 200 OK
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=115000' | head -n1
HTTP/1.1 400 Bad Request
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=112000' | head -n1
HTTP/1.1 400 Bad Request
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=111700' | head -n1
HTTP/1.1 400 Bad Request
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=111600' | head -n1
HTTP/1.1 400 Bad Request
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=111500' | head -n1
HTTP/1.1 400 Bad Request
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=111400' | head -n1
HTTP/1.1 200 OK
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=111450' | head -n1
HTTP/1.1 400 Bad Request
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=...&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=111430' | head -n1
HTTP/1.1 200 OK
```

So the limit is around 111430? But if I restart Loki, the upper limit before it bugs out with `Bad Request` isn't exactly the same. Some kind of buffer issue?

Anyway, I fully expect Loki to be able to stream my _entire_ log history via `logcli`. Unfortunately, this isn't possible. I would have expected `logcli --limit=2147483647` to work, and indeed that used to work for me a few upgrades ago, but these days I consistently get `Bad Request` for high limits.

There's no explanation in the response about what the cause of the bad request — actually the body is just `EOF`:

```
$ curl -s -i 'http://loki.ops.svc.cluster.local:3100/api/prom/query?query=....&start=1580765727779481488&end=1580772927779481488&direction=FORWARD&regexp=&limit=200000'
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 04 Feb 2020 00:01:04 GMT
Content-Length: 4

EOF
```

Nothing in Loki's stdout/stderr.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: N/A
 - Version: 1.3.0

**Comment by cyriltovena** [comment] 2020-02-04 14:21
So I'm not able to reproduce this, I blew up my chrome with 115000 lines. I even added a tests and it seems to parse the limit correctly. Could it be related to the logcli or you're using curl ? Which version are you running ? Are you using helm or ksonnet ?

**Comment by atombender** [comment] 2020-02-04 16:03
For this, I'm using `curl` directly, though I'm also seeing it with `logcli`.

I'm using my own custom Helm chart. Loki 1.3.0.

**Comment by cyriltovena** [comment] 2020-02-04 16:08
Can you share you config so I can try to reproduce it ? How is your custom chart different ?

**Comment by atombender** [comment] 2020-02-04 16:12
```yaml
auth_enabled: false
ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 3m
  chunk_block_size: 262144
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
limits_config:
  enforce_metric_name: false
schema_config:
  configs:
  - from: 2019-06-23
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /mnt/data/loki/index
  filesystem:
    directory: /mnt/data/loki/chunks
chunk_store_config:
  max_look_back_period: 0
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
```

I built our Helm chart from scratch, because reasons. 🙂

**Comment by slim-bean** [comment] 2020-02-05 01:06
how long is your query taking before it returns the 400?

There is a limit on how long a query can execute before it's terminated which defaults to 1 minute

You can change this with the `query_timeout` see [here](https://github.com/grafana/loki/tree/master/docs/configuration#querier_config) for more info.

It looks like this timeout could likely produce a timeout with no body.

It's also probably worth noting that even if this does help, there is still going to be some ultimate limit on how much data you can return before you OOM something.  The API's as written today are not streaming and need to load all the data up to the specified limit before returning the result.

This may change in the future as we are looking at options for streaming results but for now if you really need to get huge amounts of data you would need to look at paging your requests into manageable sizes

**Comment by atombender** [comment] 2020-02-05 01:09
Just a second or two. I don't see how it can be a timeout.

**Comment by slim-bean** [comment] 2020-02-05 01:29
I'm not able to reproduce this either.  If i make a request for 1mil lines I just get an error like this:

`Query failed: Error response from server: response larger than the max (260072437 vs 104857600) (<nil>)`

This is doing a label only query with no filter expression.  What kind of query are you sending?

**Comment by atombender** [comment] 2020-02-05 16:49
I'm doing pure label queries with no filter. I just tried another one, and it worked fine. Maybe it's completely unrelated. I will see if I can reproduce.

Might be worth checking the code for places where `400` is returned, and also where naked `err` values are returned without wrapping in something like `fmt.Errorf("blah: %w", err)`.

**Comment by cyriltovena** [comment] 2020-02-06 11:53
Could be a limit ?

**Comment by cyriltovena** [comment] 2020-03-11 13:10
I'm wondering if your Loki is not crashing ? I've seen something similar today although we run a distributed version.

**Comment by zaafar** [comment] 2020-03-20 20:27
We (the company I work in) are also seeing this bug intermittently (in our nightly pipeline). Sad news is that I have not been able to reproduce it locally. Right after it happened, I sent the exact same HTTP request and got a valid response. Here's my input for this bug.

==Loki Version==
If this information isn't enough, let me know.
> loki, version v1.3.0 (branch: HEAD, revision: 5e527a03)
>  build user:       root@ac8d743b69c3
>  build date:       2020-01-25T23:24:58Z
>  go version:       go1.13.6


==REQUEST & RESPONSE==

> * TCP_NODELAY set
> * Connected to monitor-loki.monitoring (10.102.107.237) port 3100 (#0)
> > GET /loki/api/v1/query_range?query=%7Bnamespace%3D%22cenxci200675%22%7D&start=1584721224000000000&direction=forward&limit=100000000 HTTP/1.1
> > Host: monitor-loki.monitoring:3100
> > User-Agent: curl/7.67.0
> > Accept: \*/\*
> > 
> * Mark bundle as not supporting multiuse
> > HTTP/1.1 400 Bad Request
> > Content-Type: text/plain; charset=utf-8
> > X-Content-Type-Options: nosniff
> > Date: Fri, 20 Mar 2020 16:35:25 GMT
> > Content-Length: 4
> > 

==Misc Details==
* According to the `kubectl pods` command loki server did not crash
`monitor-loki-0                                           1/1     Running   0          2d4h`

* We had seen the similar bug when using the deprecated `/api/prom/query` API.

* We are requesting a lot of logs in that REST call.

**Comment by cyriltovena** [comment] 2020-03-20 21:33
It's probably a crash related to the allocation required to run that query.
What we need to fix this is some sort of streaming API. For now you can
batch your request using the last timestamp received as the next start.

Le ven. 20 mars 2020 à 16:27, Zaafar Ahmed <notifications@github.com> a
écrit :

**Comment by atombender** [comment] 2020-03-20 21:36
In my case it's not a crash; Loki does not report any errors to the log, and the process stays up.

**Comment by zaafar** [comment] 2020-03-20 22:43
> It's probably a crash related to the allocation required to run that query.
> In my case it's not a crash; Loki does not report any errors to the log, and the process stays up

Same here, Loki doesn't show any ERROR/WARNING logs (as shown in my previous msg). So if it's a crash (thread crashing etc), it's probably hidden behind a try/catch statement.

**Comment by cyriltovena** [comment] 2020-03-28 18:56
The real solution to this issue is a streaming API. You might not see any errors but I think it's because it's handled, have you check memory limits and usage of Loki when doing such queries ?

**Comment by slim-bean** [comment] 2020-08-27 13:21
Closing this issue, ultimately the solution to this problem is as Cyril said, a streaming API. In practice the current API has many limitations that make it difficult to field extremely large requests. Batching requests will always be required against the current endpoint. Logcli 1.6.0 includes batching support now as a way to accommodate very large requests.

**Closed by slim-bean** 2020-08-27 13:21 UTC
Labels: component/loki, keepalive, kind/bug

**Comment by vdesplanque** [comment] 2020-10-08 13:15
Hi, as I understand, this should no longer be an issue to make a query to loki with high limit with 1.6.0 version thanks to the new batch feature.
Unfortunately, I encounter the same problem with a tiny limit of 5000, while the request works fine with 1000.

==Loki Version==
Containers:
  loki:
    Container ID:  docker://d29862c0f48a8d4ef1657fe457b5e1c4dbe5fcff0040ea8b8ee39514c455322d
    Image:         grafana/loki:1.6.0

It was deployed on a kubernetes setup with helm chart from grafana.

Here is the .net code that I execute : 
`return await _httpClient.GetStreamAsync($"/loki/api/v1/query_range?{queryParameters}");`

Which correspond to this request :
`http://{server}:{port}/loki/api/v1/query_range?query={app="bridge"}&limit=5000&start=1601557572275000000&end=1602162372275000000`
-> 'Response status code does not indicate success: 400 (Bad Request).'

It works well with this request:
`http://{server}:{port}/loki/api/v1/query_range?query={app="bridge"}&limit=1000&start=1601557572275000000&end=1602162372275000000`

Is there something I did wrong ? Should I fill a new bug ?

**Comment by vdesplanque** [comment] 2020-10-13 08:45
Hi,
It seems that the problem was caused by the default configuration : 
[max_entries_limit_per_query: <int> | default = 5000 ]

**Comment by slim-bean** [comment] 2020-10-13 11:42
Also note the batching in 1.6.0 is only a feature of logcli, no changes were made to the Loki API itself.

The only batching you can get is by using logcli 1.6.0 or newer, if you are directly consuming the Loki API you need to do the batching yourself still.

**Comment by vdesplanque** [comment] 2020-10-13 12:30
Hum ok, thanks for the information.
Will this batching feature be added to the API in the future ?

I have another question which is not related to the initial bug but perhaps you can point me to some doc.
I was not able to have the "max_entries_limit_per_query" configured, is it possible to configure this while installing loki with helm chart ?
This parameter seems to not be part of the [loki helm configuration](https://github.com/grafana/loki/blob/master/production/helm/loki/values.yaml)
