### ISSUE TITLE
Loki 1.5.0: The "loki-loki-stack" ConfigMap is not created for "loki-stack-datasource.yaml"

### ISSUE THREAD

**Issue by k8s42** [grafana/loki#2195] opened 2020-06-08 14:37 UTC
**Describe the bug**
I deployed the Loki Stack (stable) using Helm 3 and Loki 1.5.0 was deployed but no ConfigMap was created for the "loki-stack-datasource.yaml" file.

**To Reproduce**
1. Add repo:
helm3 repo add loki https://grafana.github.io/loki/charts
2. Deploy Loki Stack using Helm 3:
helm3 --install --name=loki loki/loki-stack
3. List ConfigMaps in Loki namespace:
kubectl get configmaps -n loki
NAME                   DATA   AGE
loki-loki-stack-test   1      6m19s
loki-promtail             1      6m19s

**Expected behavior**
The "loki-loki-stack" should've been created for "loki-stack-datasource.yaml".

**Environment:**
 - Infrastructure: Kubernetes v1.15.10
 - Deployment tool: Helm3
 - Loki: v1.5.0

**Screenshots, Promtail config, or terminal output**
This was not an issue in Loki 1.4.1.

**Comment by cyriltovena** [comment] 2020-06-08 14:40
is this a duplicate of #2186 ? Can you confirm ?

**Closed** 2020-06-22 12:48 UTC
