### ISSUE TITLE
Support nested folders inside s3 bucket

### ISSUE THREAD

**Issue by guvmao** [grafana/loki#5690] opened 2022-03-22 03:20 UTC
**Is your feature request related to a problem? Please describe.**
When storing data in S3, it can only be stored in the root directory. Cannot store inside nested folders.

**Describe the solution you'd like**
Specify an option, such as `Prefix`, to set where the data is stored in the S3 bucket. `BucketName/FolderName/index`

**Comment by SilverPhoenix99** [comment] 2022-03-26 12:21
I have a couple of use cases for this:
1. In some organizations, the S3 buckets are managed by IT, while each team only manages the contents of their own assigned bucket. Without being able to create buckets, the team could define a prefix for Loki data on their own bucket. While this use case doesn't apply specifically to me, it could provide teams with some independence.
2. In my particular case, I've been having permission issues after creating new buckets, and until I'm able to sort it, or as a permanent alternative, I could have had Loki run in one of the other buckets that are working fine, under a prefix.

**Comment by dennisgeerts** [comment] 2022-04-22 19:48
I'm having the same issue. 
If I want to run Loki for 2 environments, should i be creating two S3 buckets ?

**Comment by dannykopping** [comment] 2022-09-28 07:49
Duplicate of #5889

**Closed by dannykopping** 2022-09-28 07:49 UTC
Labels: component/storage
