### ISSUE TITLE
Server misbehaving

### ISSUE THREAD

**Issue by k-szortyka** [grafana/loki#5349] opened 2022-02-08 22:57 UTC
**Describe the bug**
I have Grafana, Loki and promtail on docker container and I am deploying the same using docker-compose file. When I am trying to add datasource in grafana then getting error : 
lut 08 23:50:10  dockerd[16670]: time="2022-02-08T23:50:10+01:00" level=info msg="level=warn ts=2022-02-08T22:50:10.715109709Z caller=client.go:349 container_id=2a8efeb7b4ae3226cf56d9a6595d51f24e9855e15cf079534e58f5c6d52805b6 component=client host=loki:3100 msg=\"error sending batch, will retry\" status=-1 error=\"Post \\\"http://loki:3100/loki/api/v1/push\\\": dial tcp: lookup loki on 127.0.0.53:53: server misbehaving\"" plugin=0e31af881665fe70c593d7feae8015465267fbfaf92144c815d160cae964b91

And I don't show docker logs in Grafana. I have only filename and job.

**To Reproduce**
Deploy container using docker-compose file
Trying to add datasource in grafana
No show label with container logs

**Expected behavior**
Show docker logs in Grafana.

**Environment:**
Host Machine : Ubuntu 20.04
Grafana Version : 8.4.2
Loki and Promtail version : 2.4.2

**Screenshots, Promtail config, or terminal output**
docker-compose.yml
version: "3.6"
networks:
  loki:
services:
  loki:
    image: grafana/loki:2.4.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:2.4.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /etc/promtail/docker-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

promtail-config
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: containers

  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  # --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  pipeline_stages:

  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: "tag"

  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:

**Comment by dannykopping** [comment] 2022-02-09 08:46
This seems like an issue with your local DNS resolver in docker, and not related to Loki.
[Here's another user having a similar problem with docker](https://stackoverflow.com/questions/28332845/docker-network-issue-server-misbehaving/34833611).

I'm closing this for now but please reopen if you dig deeper and find that the issue is originating from Loki or related components.

**Closed by dannykopping** 2022-02-09 08:46 UTC

**Comment by KES777** [comment] 2022-11-01 00:36
@k-szortyka: refer to your loki instance by static IP and not by name. loki plugin is not on your stack network and thus do not have access to service's names. Look [here](https://github.com/grafana/loki/issues/1368#issuecomment-1297848723) for details.
