### ISSUE TITLE
too many outstanding requests on v2.4.2

### ISSUE THREAD

**Issue by benisai** [grafana/loki#5851] opened 2022-04-11 04:42 UTC
**Describe the bug**

**To Reproduce**
1. Started Loki v2.4.2
2. Started Promtail (SHA or version) to tail '...' -- NA
3. Query: `{} term` -- Anything

**Expected behavior**
too many outstanding requests on v2.4.2

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] --- ubuntu + Docker engine
 - Deployment tool: [e.g., helm, jsonnet] -- docker-compose

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**### too many outstanding requests on v2.4.2**

**Comment by benisai** [comment] 2022-04-11 04:43
Loki team, please roll back v2.4.2, its broken. 2.4.1 does not have issues.

**Comment by dannykopping** [comment] 2022-04-11 05:45
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Closed by dannykopping** 2022-04-11 05:45 UTC

**Comment by benisai** [comment] 2022-04-11 05:50
This is a bug. Please reopen.

**Comment by dannykopping** [comment] 2022-04-11 06:46
This is not a bug. This error occurs when there are too many queries in the queue.
Please use the channels above to get further assistance with this problem.
