### ISSUE TITLE
panic: exemplar labels have 85 runes, exceeding the limit of 64

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#6667] opened 2022-07-12 13:16 UTC
**Describe the bug**

	/Users/fuling/go/pkg/mod/github.com/liguozhong/loki@v1.6.2-0.20220712032519-992e483b6271/pkg/storage/chunk/cache/instrumented.go:95 +0x1af

here

![image](https://user-images.githubusercontent.com/9583245/178498747-51f5d11e-f3d9-4301-ba79-640d817efef7.png)

![image](https://user-images.githubusercontent.com/9583245/178527150-1f9e285c-d70e-49e4-819f-a5634c79f626.png)

https://github.com/prometheus/client_golang/blob/main/prometheus/value.go
![image](https://user-images.githubusercontent.com/9583245/178498657-59f0a3fa-06fa-44b2-9a9a-51a309859cee.png)

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by bboreham** [comment] 2022-07-19 10:30
Should be addressed by https://github.com/weaveworks/common/pull/247.
Also note https://github.com/prometheus/client_golang/pull/1091

**Comment by John-Lin** [comment] 2022-07-20 06:01
Same issue here when we upgrade to distributed Loki v2.6.1. distributors have same error message. 
We disable the [tracing feature](https://grafana.com/docs/loki/latest/configuration/#tracing) for workaround.

**Comment by liguozhong** [comment] 2022-08-31 13:31
this pr has fix this issue.
https://github.com/grafana/loki/pull/6859

**Comment by periklis** [comment] 2022-08-31 13:35
Isn't this address by #6957 already?

**Comment by liguozhong** [comment] 2022-09-02 08:31
6859>6957 , so I don't think 6957 has fixed this yet

**Comment by periklis** [comment] 2022-09-02 08:44
The issue is imho fixed by bumping the prometheus/client_golang to 1.13 with #6957. The changelog of client_golang (https://github.com/prometheus/client_golang/releases/tag/v1.13.0) mentions:
```
[BUGFIX] Raise exemplar labels limit from 64 to 128 bytes as specified in OpenMetrics spec. https://github.com/prometheus/client_golang/pull/1091
```

**Comment by bboreham** [comment] 2022-09-02 09:09
[One change](https://github.com/weaveworks/common/pull/247) removes the thing that made exemplar labels longer, [the other](https://github.com/prometheus/client_golang/pull/1091) raises the exemplar length limit.

Either way I agree it can be closed.

**Closed by bboreham** 2022-09-02 09:09 UTC
