### ISSUE TITLE
Loki build fail

### ISSUE THREAD

**Issue by Abuelodelanada** [grafana/loki#7854] opened 2022-12-05 15:04 UTC
**Describe the bug**

It is not possible to build loki (`main` branch)

**To Reproduce**
1. Started Loki (`main` branch, commit: [`85392a972`](https://github.com/canonical/loki/commit/85392a9728b3b6e949fd2da70b04ebdfedfe6c69))
2. Run `make loki`
3. You'll get:
```shell
➜  loki git:(main) ✗ make loki
CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w -X github.com/grafana/loki/pkg/util/build.Branch=main -X github.com/grafana/loki/pkg/util/build.Version=main-85392a9 -X github.com/grafana/loki/pkg/util/build.Revision=85392a972 -X github.com/grafana/loki/pkg/util/build.BuildUser=jose@miguelito -X github.com/grafana/loki/pkg/util/build.BuildDate=2022-12-05T14:50:59Z" -tags netgo -o cmd/loki/loki ./cmd/loki
go: downloading github.com/weaveworks/common v0.0.0-20221201103051-7c2720a9024d
pkg/querier/series/series_set.go:23:2: no required module provides package github.com/prometheus/prometheus/model/histogram; to add it:
	go get github.com/prometheus/prometheus/model/histogram
pkg/ruler/base/compat.go:15:2: no required module provides package github.com/prometheus/prometheus/model/metadata; to add it:
	go get github.com/prometheus/prometheus/model/metadata
pkg/util/wal/reader.go:7:2: no required module provides package github.com/prometheus/prometheus/tsdb/wlog; to add it:
	go get github.com/prometheus/prometheus/tsdb/wlog
make: *** [Makefile:138: cmd/loki/loki] Error 1
```
4. Install missing modules:

```shell
➜  loki git:(main) ✗ go get github.com/prometheus/prometheus/model/histogram
➜  loki git:(main) ✗ go get github.com/prometheus/prometheus/model/metadata
➜  loki git:(main) ✗ go get github.com/prometheus/prometheus/tsdb/wlog
go: downloading golang.org/x/exp v0.0.0-20221031165847-c99f073a8326
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
```

5. Run `make loki` again and you will get the same error again:

```shell
➜  loki git:(main) ✗ make loki                                              
CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w -X github.com/grafana/loki/pkg/util/build.Branch=main -X github.com/grafana/loki/pkg/util/build.Version=main-85392a9 -X github.com/grafana/loki/pkg/util/build.Revision=85392a972 -X github.com/grafana/loki/pkg/util/build.BuildUser=jose@miguelito -X github.com/grafana/loki/pkg/util/build.BuildDate=2022-12-05T14:55:54Z" -tags netgo -o cmd/loki/loki ./cmd/loki
pkg/querier/series/series_set.go:23:2: no required module provides package github.com/prometheus/prometheus/model/histogram; to add it:
	go get github.com/prometheus/prometheus/model/histogram
pkg/ruler/base/compat.go:15:2: no required module provides package github.com/prometheus/prometheus/model/metadata; to add it:
	go get github.com/prometheus/prometheus/model/metadata
pkg/util/wal/reader.go:7:2: no required module provides package github.com/prometheus/prometheus/tsdb/wlog; to add it:
	go get github.com/prometheus/prometheus/tsdb/wlog
make: *** [Makefile:138: cmd/loki/loki] Error 1
```

**Expected behavior**
I expect loki is built correctly

**Environment:**
 - SO: Ubuntu 22.04 (amd64)
 - go version: 1.19.3

**Comment by DylanGuedes** [comment] 2022-12-05 17:14
I can't reproduce this, even after running `go clean`:
```
dguedes@fedora ~/Workspace/github.com/grafana/loki (main) $ go clean
dguedes@fedora ~/Workspace/github.com/grafana/loki (main) $ make loki
CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w -X github.com/grafana/loki/pkg/util/build.Branch=main -X github.com/grafana/loki/pkg/util/build.Version=main-2e496dd -X github.com/grafana/loki/pkg/util/build.Revision=2e496ddff -X github.com/grafana/loki/pkg/util/build.BuildUser=dguedes@fedora -X github.com/grafana/loki/pkg/util/build.BuildDate=2022-12-05T17:13:51Z" -tags netgo -o cmd/loki/loki ./cmd/loki
-> success
```
go version
go version go1.19.3 linux/amd64
```

**Comment by Abuelodelanada** [comment] 2022-12-05 20:00
In a fresh new installed ubuntu 22.04 I can reproduce it:

```shell
╭─ubuntu@charm-dev-juju-3 ~/repos/loki ‹main●› 
╰─$ make loki
CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w -X github.com/grafana/loki/pkg/util/build.Branch=main -X github.com/grafana/loki/pkg/util/build.Version=main-85392a9-WIP -X github.com/grafana/loki/pkg/util/build.Revision=85392a972 -X github.com/grafana/loki/pkg/util/build.BuildUser=ubuntu@charm-dev-juju-3 -X github.com/grafana/loki/pkg/util/build.BuildDate=2022-12-05T19:55:44Z" -tags netgo -o cmd/loki/loki ./cmd/loki
go: downloading github.com/dannykopping/go-kit-log v0.2.2-0.20221002180827-5591c1641b6b
go: downloading github.com/prometheus/client_golang v1.13.1
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/weaveworks/common v0.0.0-20221201103051-7c2720a9024d
go: downloading github.com/prometheus/prometheus v1.8.2-0.20220303173753-edfe657b5405
go: downloading github.com/drone/envsubst v1.0.2
go: downloading github.com/grafana/dskit v0.0.0-20220928083349-b1b307db4f30
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/text v0.4.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/prometheus/common/sigv4 v0.1.0
go: downloading golang.org/x/time v0.1.0
go: downloading github.com/NYTimes/gziphandler v1.1.1
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/felixge/fgprof v0.9.2
go: downloading github.com/thanos-io/thanos v0.28.0
go: downloading google.golang.org/grpc v1.45.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/opentracing/opentracing-go v1.2.0
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/stretchr/testify v1.8.1
go: downloading go.uber.org/atomic v1.10.0
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/weaveworks/promrus v1.2.0
go: downloading github.com/uber/jaeger-client-go v2.30.0+incompatible
go: downloading github.com/uber/jaeger-lib v2.4.1+incompatible
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/grafana/regexp v0.0.0-20221005093135-b4c2bcb0a4b6
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/go-logfmt/logfmt v0.5.1
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
go: downloading github.com/opentracing-contrib/go-grpc v0.0.0-20210225150812-73cb765af46e
go: downloading github.com/prometheus/exporter-toolkit v0.8.2
go: downloading golang.org/x/net v0.1.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/c2h5oh/datasize v0.0.0-20200112174442-28bbd4740fee
go: downloading github.com/aws/aws-sdk-go v1.44.128
go: downloading github.com/alecthomas/units v0.0.0-20211218093645-b94a6e3cc137
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/gogo/status v1.1.1
go: downloading github.com/armon/go-metrics v0.4.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/grafana/memberlist v0.3.1-0.20220714140823-09ffed8adbbe
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/opentracing-contrib/go-stdlib v1.0.0
go: downloading github.com/google/pprof v0.0.0-20221102093814-76f304f74e5e
go: downloading github.com/imdario/mergo v0.3.12
go: downloading github.com/spf13/afero v1.9.2
go: downloading github.com/owen-d/gomemcache v0.0.0-20220719101501-ce4268ea75ae
go: downloading github.com/facette/natsort v0.0.0-20181210072756-2cd4dd1e2dcb
go: downloading github.com/go-redis/redis/v8 v8.11.5
go: downloading github.com/sony/gobreaker v0.5.0
go: downloading github.com/klauspost/compress v1.15.11
go: downloading github.com/go-redis/redis v6.15.9+incompatible
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/felixge/httpsnoop v1.0.3
go: downloading github.com/gogo/googleapis v1.4.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2
go: downloading github.com/stretchr/objx v0.5.0
go: downloading google.golang.org/genproto v0.0.0-20221027153422-115e99e71e1c
go: downloading golang.org/x/sys v0.1.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading github.com/julienschmidt/httprouter v1.3.0
go: downloading github.com/edsrzf/mmap-go v1.1.0
go: downloading go.opentelemetry.io/otel v1.11.1
go: downloading go.opentelemetry.io/otel/trace v1.11.1
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.36.4
go: downloading github.com/oklog/ulid v1.3.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/sercand/kuberesolver v2.4.0+incompatible
go: downloading github.com/coreos/go-systemd/v22 v22.4.0
go: downloading go.opentelemetry.io/contrib v0.20.0
go: downloading golang.org/x/crypto v0.1.0
go: downloading github.com/coreos/go-systemd v0.0.0-20191104093116-d3cd4ed1dbcf
go: downloading github.com/Masterminds/sprig/v3 v3.2.2
go: downloading github.com/Masterminds/sprig v2.16.0+incompatible
go: downloading inet.af/netaddr v0.0.0-20211027220019-c74959edd3b6
go: downloading github.com/mwitkow/go-conntrack v0.0.0-20190716064945-2f068394615f
go: downloading golang.org/x/oauth2 v0.1.0
go: downloading github.com/hashicorp/consul/api v1.15.3
go: downloading go.etcd.io/etcd/api/v3 v3.5.4
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
go: downloading go.etcd.io/etcd v3.3.25+incompatible
go: downloading github.com/hashicorp/consul v1.5.1
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.4
go: downloading go.etcd.io/etcd/client/v3 v3.5.4
go: downloading github.com/hashicorp/go-immutable-radix v1.3.1
go: downloading github.com/Workiva/go-datastructures v1.0.53
go: downloading github.com/pierrec/lz4/v4 v4.1.17
go: downloading github.com/google/btree v1.0.1
go: downloading github.com/hashicorp/go-msgpack v0.5.5
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/miekg/dns v1.1.50
go: downloading github.com/sean-/seed v0.0.0-20170313163322-e2103e2c3529
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/dennwc/varint v1.0.0
go: downloading github.com/minio/minio-go/v7 v7.0.32-0.20220706200439-ef3e45ed9cdb
go: downloading github.com/Azure/azure-pipeline-go v0.2.3
go: downloading github.com/MasslessParticle/azure-storage-blob-go v0.14.1-0.20220216145902-b5e698eff68e
go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.21
go: downloading github.com/Azure/go-autorest/autorest/azure/auth v0.5.11
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/Azure/go-autorest/autorest v0.11.28
go: downloading github.com/baidubce/bce-sdk-go v0.9.111
go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
go: downloading cloud.google.com/go/bigtable v1.3.0
go: downloading cloud.google.com/go/storage v1.27.0
go: downloading cloud.google.com/go v0.105.0
go: downloading github.com/fsouza/fake-gcs-server v1.7.0
go: downloading google.golang.org/api v0.102.0
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/cristalhq/hedgedhttp v0.7.0
go: downloading github.com/ncw/swift v1.0.53
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading github.com/prometheus/alertmanager v0.24.0
go: downloading github.com/oklog/run v1.1.0
go: downloading github.com/thanos-io/objstore v0.0.0-20220715165016-ce338803bc1e
go: downloading github.com/grafana/gocql v0.0.0-20200605141915-ba5dc39ece85
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: downloading go.uber.org/goleak v1.2.0
go: downloading github.com/go-logr/logr v1.2.3
go: downloading go.opentelemetry.io/otel/metric v0.33.0
go: downloading github.com/Masterminds/goutils v1.1.1
go: downloading github.com/Masterminds/semver/v3 v3.1.1
go: downloading github.com/huandu/xstrings v1.3.1
go: downloading github.com/Masterminds/semver v1.4.2
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading github.com/shopspring/decimal v1.2.0
go: downloading github.com/spf13/cast v1.3.1
go: downloading go4.org/intern v0.0.0-20211027215823-ae77deb06f29
go: downloading github.com/jpillora/backoff v1.0.0
go: downloading go.uber.org/zap v1.21.0
go: downloading github.com/hashicorp/go-hclog v0.16.2
go: downloading github.com/hashicorp/serf v0.9.7
go: downloading github.com/hashicorp/go-rootcerts v1.0.2
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
go: downloading github.com/Azure/go-autorest/logger v0.2.1
go: downloading github.com/Azure/go-autorest/tracing v0.6.0
go: downloading github.com/golang-jwt/jwt/v4 v4.4.1
go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.4.5
go: downloading github.com/dimchansky/utfbom v1.1.1
go: downloading cloud.google.com/go/iam v0.6.0
go: downloading cloud.google.com/go/longrunning v0.1.1
go: downloading github.com/golang-jwt/jwt v3.2.1+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.6.0
go: downloading github.com/googleapis/gax-go v2.0.2+incompatible
go: downloading rsc.io/binaryregexp v0.2.0
go: downloading cloud.google.com/go/compute/metadata v0.2.1
go: downloading go.opencensus.io v0.23.0
go: downloading github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d
go: downloading cloud.google.com/go/compute v1.12.1
go: downloading github.com/go-openapi/errors v0.20.2
go: downloading go.mongodb.org/mongo-driver v1.10.2
go: downloading github.com/efficientgo/tools/core v0.0.0-20220225185207-fe763185946b
go: downloading github.com/aws/aws-sdk-go-v2 v1.16.0
go: downloading github.com/aws/aws-sdk-go-v2/config v1.15.1
go: downloading github.com/go-kit/kit v0.12.0
go: downloading github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading github.com/mitchellh/reflectwalk v1.0.1
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading go4.org/unsafe/assume-no-moving-gc v0.0.0-20220617031537-928513b29760
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/go-openapi/swag v0.21.1
go: downloading github.com/go-openapi/validate v0.21.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/klauspost/cpuid/v2 v2.0.14
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.2.0
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading gopkg.in/ini.v1 v1.66.6
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/go-openapi/analysis v0.21.2
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/go-openapi/loads v0.21.1
go: downloading github.com/go-openapi/spec v0.20.5
go: downloading github.com/aws/smithy-go v1.11.1
go: downloading github.com/aws/aws-sdk-go-v2/credentials v1.11.0
go: downloading github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.1
go: downloading github.com/aws/aws-sdk-go-v2/internal/ini v1.3.8
go: downloading github.com/aws/aws-sdk-go-v2/service/sso v1.11.1
go: downloading github.com/aws/aws-sdk-go-v2/service/sts v1.16.1
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/rs/xid v1.4.0
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/go-openapi/jsonreference v0.20.0
go: downloading github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.7
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.1
go: downloading github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.1
pkg/querier/series/series_set.go:23:2: no required module provides package github.com/prometheus/prometheus/model/histogram; to add it:
	go get github.com/prometheus/prometheus/model/histogram
pkg/ruler/base/compat.go:15:2: no required module provides package github.com/prometheus/prometheus/model/metadata; to add it:
	go get github.com/prometheus/prometheus/model/metadata
pkg/util/wal/reader.go:7:2: no required module provides package github.com/prometheus/prometheus/tsdb/wlog; to add it:
	go get github.com/prometheus/prometheus/tsdb/wlog
make: *** [Makefile:138: cmd/loki/loki] Error 1
```

and..

```shell
╭─ubuntu@charm-dev-juju-3 ~/repos/loki ‹main●› 
╰─$ go version 
go version go1.19.3 linux/amd64
```

**Comment by Abuelodelanada** [comment] 2022-12-06 20:57
This is my `go env`

```shell
➜  loki git:(main) ✗ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/jose/go/bin"
GOCACHE="/home/jose/.cache/go-build"
GOENV="/home/jose/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jose/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jose/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/9994"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/9994/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="/usr/bin/gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jose/trabajos/canonical/repos/loki/go.mod"
GOWORK="/home/jose/trabajos/canonical/repos/loki/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1655941090=/tmp/go-build -gno-record-gcc-switches"
```


After turning off `GOWORK`:

```shell
➜  loki git:(main) ✗ export GOWORK=off 
➜  loki git:(main) ✗ go env | grep WORK
GOWORK="off"
```

I'm now able to build Loki:

```shell
➜  loki git:(main) ✗ make loki                                                       
CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w -X github.com/grafana/loki/pkg/util/build.Branch=main -X github.com/grafana/loki/pkg/util/build.Version=main-fee2374 -X github.com/grafana/loki/pkg/util/build.Revision=fee237453 -X github.com/grafana/loki/pkg/util/build.BuildUser=jose@miguelito -X github.com/grafana/loki/pkg/util/build.BuildDate=2022-12-06T20:56:24Z" -tags netgo -o cmd/loki/loki ./cmd/loki
```

**Comment by MichelHollands** [comment] 2022-12-16 11:24
This was due to a wrong update of the prometheus dependencies. This is fixed now.

**Closed by MichelHollands** 2022-12-16 11:24 UTC
