### ISSUE TITLE
runtime: program exceeds 10000-thread limit

### ISSUE THREAD

**Issue by oskoi** [grafana/loki#228] opened 2019-01-18 22:01 UTC
I'm trying to search logs for a day and get this...
[loki.log](https://github.com/grafana/loki/files/2774651/loki.log)

loki:
repository: grafana/loki
tag: master

promtail:
repository: grafana/promtail
tag: master 

for installation used helm https://github.com/grafana/loki/tree/master/production/helm

**Comment by daixiang0** [comment] 2019-01-21 05:53
Could you share more details? Maybe the way to reproduce?

**Comment by tomwilkie** [comment] 2019-02-18 15:06
Going to close as a dupe of #227

**Closed by tomwilkie** 2019-02-18 15:06 UTC
