### ISSUE TITLE
Loki: Bad Gateway. 502. Bad Gateway

### ISSUE THREAD

**Issue by bsstoandv** [grafana/loki#4970] opened 2021-12-20 06:28 UTC
Issues when add Loki data source on Grafana
**Loki: Bad Gateway. 502. Bad Gateway**

When I tried to add Loki data source to grafana I got 502 bat gateway.
I deployed grafana, prometheus, loki on docker swarm. All container using same network `monitor-net` and all containers are running with no errors.

![image](https://user-images.githubusercontent.com/96405188/146721735-be16459a-e6e1-499e-b8d4-ea3b95a8ffac.png)

With prometheus. I can add datasource with no error by using this url `http://prometheus:9090` 
Can some one help me with this?

This is my compose file:
```yaml
version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  monitor-net:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
#      - pushgateway
    networks:
      - monitor-net
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:2.4.0
    depends_on:
      - promtail
    ports:
      - "3100:3100"
    volumes:
      - ./loki/:/etc/loki/
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor-net
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - ./promtail/:/etc/promtail/
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - monitor-net
    deploy:
      mode: global
      restart_policy:
          condition: on-failure

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    networks:
      - monitor-net
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      placement:
        constraints:
           - node.role==manager
      restart_policy:
        condition: on-failure    

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - monitor-net
    deploy:
      mode: global
      restart_policy:
          condition: on-failure

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - monitor-net
    user: "472"
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

#  pushgateway:
#    image: prom/pushgateway
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
#    ports:
#      - 9091:9091
#    networks:
#      - monitor-net

```

**Comment by DylanGuedes** [comment] 2021-12-20 09:59
could you share your loki configuration YAML? Some users experienced issues when running in Docker Swarm, and the solution was to specify a `127.0.0.1` address to be advertised by Loki components. You can do that by merging the following configurations at your YAML:
```yaml
frontend:
  address: 127.0.0.1
common:
  ring:
    instance_addr: 127.0.0.1
```

**Comment by bsstoandv** [comment] 2021-12-20 10:53
> could you share your loki configuration YAML? Some users experienced issues when running in Docker Swarm, and the solution was to specify a `127.0.0.1` address to be advertised by Loki components. You can do that by merging the following configurations at your YAML:
> 
> ```yaml
> frontend:
>   address: 127.0.0.1
> common:
>   ring:
>     instance_addr: 127.0.0.1
> ```

**Comment by bsstoandv** [comment] 2021-12-21 01:35
Dear @DylanGuedes ,
I remove docker stack and try to run with docker-compose and it working well.
I can add loki data source now.
But I wonder why we have problem with docker swarm ?

**Comment by DylanGuedes** [comment] 2021-12-22 10:54
Just double checking, did you try adding `frontend: address: 127.0.0.1` to your Loki configuration deployed with swarm?

**Comment by dginhoux** [comment] 2021-12-22 12:51
hi, 

i'm having the same trouble.
i think problem isn't swarm mode, it's loki because in the ring configuration documentation we have two directive : https://grafana.com/docs/loki/latest/configuration/#common_config

> # Name of network interface to read addresses from.
# CLI flag: -<prefix>.instance-interface-names
[instance_interface_names: <list of string> | default = [eth0 en0]]

# IP address to advertise in the ring.
# CLI flag: -<prefix>.instance-addr
[instance_addr: <list of string> | default = first from instance_interface_names]


In swarm, it's not possible to specifiy IPaddr or interface name... so is there a way to advertise on all ip/int available ?

**Comment by zotastas-2nd** [comment] 2021-12-22 15:28
Hey there,

just to share the information. I had the same setup - loki, prometheus, grafana and several other containers running on a 3-node docker swarm. Same error: Bad Gateway. I tried your suggestion @DylanGuedes and at least for me it worked. After adding the frontend address, the connection between loki and grafana was successful.

However, the common.ring.instance_addr was already set to "localhost". I changed it to 127.0.0.1 though. Don't know, if this made any difference.

Anyway, setting your parameters solved my problem. Thank you very much :)

**Comment by DylanGuedes** [comment] 2021-12-22 16:35
> Hey there,
> 
> just to share the information. I had the same setup - loki, prometheus, grafana and several other containers running on a 3-node docker swarm. Same error: Bad Gateway. I tried your suggestion @DylanGuedes and at least for me it worked. After adding the frontend address, the connection between loki and grafana was successful.
> 
> However, the common.ring.instance_addr was already set to "localhost". I changed it to 127.0.0.1 though. Don't know, if this made any difference.
> 
> Anyway, setting your parameters solved my problem. Thank you very much :)

You're welcome! Glad It worked.
Regarding changing `common: ring: instance_addr`: unfortunately, it wouldn't be enough because the frontend isn't a ring. But, there's already [this PR](https://github.com/grafana/loki/pull/4950) that adds a common instance_addr for all Loki components, not just for rings. After we merge it, you'll be able to run it by configuring just `common: instance_addr`.

**Comment by dginhoux** [comment] 2021-12-22 16:39
instance_addr in common will change nothing in swarm/k8s deploy, because services can be handled over multiples networks and in this case, ips, or interfaces names cannot be predicated.

**Comment by DylanGuedes** [comment] 2021-12-22 16:41
instance_addr in common will work for all cases that you have to explicitly set `frontend: instance_addr`.

**Comment by dginhoux** [comment] 2021-12-22 17:02
OK, so in if I use multiples service, for split read and write targets.... What is the value to fit in this front-end addr?

I'm trying on swarm at this time and in k8s in few days.

**Comment by DylanGuedes** [comment] 2021-12-27 13:02
@dginhoux I didn't understand the question, I'm sorry. But if that helps, 100% of the Docker Swarm issues that I've seen related to this were fixed by just adding `frontend: instance_addr: 127.0.0.1` to the Loki configuration. I'm closing this one because this looks more like a duplicate of #4699, but if you find that this is clearly a different problem, feel free to open a new issue.

**Closed by DylanGuedes** 2021-12-27 13:02 UTC
