### ISSUE TITLE
Single binary Loki with memberlist config

### ISSUE THREAD

**Issue by ahmedTouati** [grafana/loki#5681] opened 2022-03-20 20:21 UTC
In Loki there are three modes monolithic, simple scalable and microservices modes, and you can run single binary loki as Horizontally scalable also according to architecture docs:
**Horizontally scale up a monolithic mode deployment to more instances by using a shared object store, and by configuring the [memberlist_config section 1](https://grafana.com/docs/loki/latest/configuration/#memberlist_config) to share state between all instances.

High availability can be configured by running two Loki instances using memberlist_config configuration and a shared object store.**

So i followed this example configuration for memberlist config ([Examples | Grafana Labs](https://grafana.com/docs/loki/latest/configuration/examples/#almost-zero-dependencyyaml)) in a single binary loki installation and increased replicas to two (loki-0,loki-1).
For join_members: i used loki headless service (loki-headless.loki.svc.cluster.local:3100) since loki-gossip-ring service is not available in this installation, but loki always fail to resolve it:

```
ts=2022-03-15T09:14:24.010697792Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-headless.loki.svc.cluster.local:3100: lookup loki-headless.loki.svc.cluster.local on 172.20.0.10:53: no such host"
```
**NOTE:** I used bind_port: 7946 then loki-headless.loki.svc.cluster.local:7946 but the port still not exposed

**Comment by dannykopping** [comment] 2022-03-21 11:11
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Closed by dannykopping** 2022-03-21 11:11 UTC

**Comment by xiaozhi747** [comment] 2022-03-23 14:24
Why is this issue closed, it is obviously not resolved  @dannykopping

**Comment by dannykopping** [comment] 2022-03-23 14:50
It's not a bug, it's a question, and we don't take questions on GitHub. We have many available channels for questions and we keep GitHub exclusively for bugs and feature requests.

**Comment by calvinbui** [comment] 2022-05-09 02:11
Simplify the endpoint to just `loki-headless`, removing `<namespace>.svc.cluster.local`.
