### ISSUE TITLE
k8s 1.18.3 

### ISSUE THREAD

**Issue by ppabloescobar** [grafana/loki#2192] opened 2020-06-06 19:48 UTC
deploy grafana-loki in k8s 1.18.3:

grafana-loki         pod/loki-0                                                        0/1     CrashLoopBackOff   6          
7m46s

kubectl logs pod/loki-0 -n grafana-loki 
standard_init_linux.go:211: exec user process caused "operation not permitted"

**Comment by invidian** [comment] 2020-06-11 10:07
This is duplicate of #2115.

**Closed** 2020-07-06 13:17 UTC
