### ISSUE TITLE
Delete log streams via API

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#577] opened 2019-05-14 03:02 UTC
**Is your feature request related to a problem? Please describe.**

When the users will want to tweak Promtail  scrape configuration (relabeling, pipeline, discovery) to work with their own deployments, they'll probably generate some unused or unwanted Loki streams.

It would be nice if we could search/filter through streams and ordered them by last chunk received, throughput and total size. Then be able to deleted those we don't want anymore.

This could also help users to create some sort of cron job to apply retention. @sandlis 

> We could use prometheus to scrape promtail and who creates those metrics. Loki could then use this to query for use within the API.

**Describe the solution you'd like**

1 - List all streams ordered by last data seen and throughout over the last 5minutes, we should be able provide label matcher `{app="mongod" cluster="us-east1"}` to narrow down the search, this should be a query limited by 100 results by default.
2 - Delete a list of stream via their labelset and may be from a specific time.

I feel like this could be useful to have in Grafana some sort of stream management UI @davkal ?

**Comment by tomwilkie** [comment] 2019-05-15 12:58
Lets try and match the Prometheus UI here: https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series

**Comment by cyriltovena** [comment] 2019-08-28 13:10
We should start with GET, https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers

/cc @davkal

**Comment by slim-bean** [comment] 2019-08-28 13:53
related to #113

**Comment by blocke** [comment] 2019-11-28 00:54
This ticket was closed but #113 only covers the GET portion. I'm hoping the DELETE portion gets included too as I just spent a couple hours fighting an incorrect timestamp parsing pipeline. Should a reminder for DELETE be added to #113 or can this ticket be saved from the stale bot?

Thanks.

**Comment by bastjan** [comment] 2020-02-17 20:38
I've hacked together a rough prototype of the delete API after seeing cortexproject/cortex#2103 and blowing up my index with an erroneously parsed timestamp.

Is anyone working on the delete API on the Loki team? I could finish up my prototype over the next 2-3 weeks if needed.

**Comment by sandeepsukhani** [comment] 2020-02-17 21:15
Not yet. I appreciate your efforts! We would like to get it working for Cortex and then reuse most of the code in Loki.
Also out of curiosity, was the issue that you were facing introduced by code from that Cortex PR? I would like to fix it if it is.

**Comment by bastjan** [comment] 2020-02-18 07:26
My issue was unrelated. I parsed the "time since boot" counter from the linux kernel log as label by accident.

The cortex PR allowed me to use the new `storage.DeleteSeriesIDs`. Which made it quite easy to implement the remainder :)

**Comment by daveram** [comment] 2020-04-23 05:17
Is there any way to manually go in and delete all instances of a label?  We're running into the scenario where we started collecting the wrong logs under the wrong label name, promtail reconfig was nice and easy but now we have the old labels hanging out with invalid logs.  Would like to clean up, and since the API doesn't support this like Prometheus yet, hoping there's a more manual way.  

We're using two different setups, one with filesystem and boltdb for chunks/index, the other with s3 and cassandra.  Both have the same scenario happening

**Comment by ayZagen** [comment] 2020-06-12 13:44
We also need this also. It would be great to have something like in prometheus. [link](https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series)

**Comment by tibin-mfl** [comment] 2020-06-15 12:19
Do we have any update on this,  Is delete api available on Loki ? 
What can we do if we want to put some on demand logs to loki for some some issue debugging and later delete that log stream.

For Example : 
We push DB logs to loki for analysing some production issue after issue debugging I don't want the logs so I need to delete that logs to reduce unnecessary storage.

**Comment by cyriltovena** [comment] 2020-06-15 12:47
It's actively being worked on by @sandeepsukhani 

Feel free to give him support, it's OpenSource !

**Comment by Tschis** [comment] 2020-07-30 11:59
@cyriltovena Hi! Thanks for the info! 💪 

But while it is not done, do you know of a workaround that can be used?
Due to some circumstances we created labels on a field that went above 100,000 entries. Now we are stuck with an error message `cardinality limit exceeded for logs{log_code}; 123474 entries, more than limit of 100000`.

Since we hold our logs for many days, is there currently any way I can manually delete these label values?

**Comment by diemus** [comment] 2020-09-16 07:42
I have to delete all data to solve the "cardinality limit exceeded for logs ....more than limit of 100000" problem. and I have no idea which label is high cardinality. is there a tool to see this? I just found the index size grow fast these days, but can not find the cause

**Comment by cyriltovena** [comment] 2020-09-16 08:53
We recently release a way to see that with logcli. (aka --analyze-labels)

see:
- https://grafana.com/blog/2020/08/13/loki-1.6.0-released-metric-query-performance-up-to-10x-faster-push-logs-from-any-client-to-promtail-query-language-and-logcli-enhancements-and-more/
- https://github.com/grafana/loki/pull/2497

It does exactly what you want ✌️

**Comment by AMoghrabi** [comment] 2020-11-05 21:19
@cyriltovena Thanks for the info. Are you aware of a way to actually delete the labels? I couldn't find information on that in the PR or blog. Thanks!

**Comment by tmikaeld** [comment] 2020-11-23 13:54
Same problem here, need to clear the logs due to GDPR request.

**Comment by sandstrom** [comment] 2021-03-17 15:47
On the topic of log deletion, I think it would be even more useful if we could configure retention. E.g. keep everything for X days/months/years.

**Comment by justinmchase** [comment] 2021-05-24 16:42
I need this also, its crazy how easy it is to add a bad label and then have it totally break your entire log database to the point where you need to wipe out all of your log data to repair it.

This should be a pretty high priority to fix imo.

**Comment by michaelkebe** [comment] 2021-08-25 08:49
Version 2.3.0 has this feature now.

https://grafana.com/docs/loki/latest/operations/storage/logs-deletion/

**Comment by 09jvilla** [comment] 2022-01-07 20:38
Closing this issue now that the log deletion api has been released.

**Closed by 09jvilla** 2022-01-07 20:38 UTC
Labels: component/loki, kind/feature, keepalive

**Comment by pgassmann** [comment] 2023-07-10 07:47
The documentation for Log deletion API has been moved here:
https://grafana.com/docs/grafana-cloud/data-configuration/logs/delete-log-lines/
https://grafana.com/docs/loki/latest/api/#request-log-deletion
