### ISSUE TITLE
Loki crash when live stream logs

### ISSUE THREAD

**Issue by mangareader** [grafana/loki#3086] opened 2020-12-17 02:30 UTC
**Describe the bug**
In explorer tab, press live stream button and loki had been crash

**To Reproduce**
1. Started Loki 2.0
2. Started Promtail 2.0
3. Query: `{job="proxy-logs"} |json | host="xxx" | line_format "{{.host}} {{.remote_addr}} {{.status}} {{.request_time}} {{.request}} "`

**Environment:**
 - Infrastructure: bare-metal

**Screenshots, Promtail config, or terminal output**
```
loki_1     | panic: runtime error: index out of range [7] with length 0
loki_1     |
loki_1     | goroutine 756038 [running]:
loki_1     | github.com/grafana/loki/pkg/logql/log.(*LabelsBuilder).Set(0xc00192f4a0, 0xc006cf6200, 0xb, 0xc006cf6210, 0xc, 0x0)
loki_1     | 	/src/loki/pkg/logql/log/labels.go:92 +0x215
loki_1     | github.com/grafana/loki/pkg/logql/log.addLabel.func1(0xc006cf6200, 0xb, 0xc006cf6210, 0xc)
loki_1     | 	/src/loki/pkg/logql/log/parser.go:35 +0xc6
loki_1     | github.com/grafana/loki/pkg/logql/log.parseMap(0x0, 0x0, 0xc0022540f0, 0xc004178640)
loki_1     | 	/src/loki/pkg/logql/log/parser.go:79 +0x3e7
loki_1     | github.com/grafana/loki/pkg/logql/log.(*JSONParser).Process(0x3963bc0, 0xc004458000, 0x309, 0x380, 0xc00192f4a0, 0xc004458000, 0xc0035b9180, 0x309, 0x380)
loki_1     | 	/src/loki/pkg/logql/log/parser.go:69 +0x144
loki_1     | github.com/grafana/loki/pkg/logql/log.(*pipeline).Process(0xc0026becc0, 0xc004458000, 0x309, 0x380, 0xc001c70000, 0x4, 0x4, 0x0, 0x0, 0x0, ...)
loki_1     | 	/src/loki/pkg/logql/log/pipeline.go:61 +0x10d
loki_1     | github.com/grafana/loki/pkg/ingester.(*tailer).processStream(0xc001bde180, 0xc0008a8e40, 0x60, 0xc00321a640, 0x3, 0x4, 0x1, 0x0, 0x1, 0xc0013e1de0, ...)
loki_1     | 	/src/loki/pkg/ingester/tailer.go:149 +0x21d
loki_1     | github.com/grafana/loki/pkg/ingester.(*tailer).send(0xc001bde180, 0xc0008a8e40, 0x60, 0xc00321a640, 0x3, 0x4, 0x0, 0x0)
loki_1     | 	/src/loki/pkg/ingester/tailer.go:121 +0x187
loki_1     | github.com/grafana/loki/pkg/ingester.(*stream).Push.func1(0xc0002c3e00, 0xc00321a640, 0x3, 0x4, 0x273d9c0, 0xc002e4a330)
loki_1     | 	/src/loki/pkg/ingester/stream.go:187 +0x23e
loki_1     | created by github.com/grafana/loki/pkg/ingester.(*stream).Push
loki_1     | 	/src/loki/pkg/ingester/stream.go:176 +0x12ac
```

**Comment by cyriltovena** [comment] 2021-01-07 16:31
Dupe of https://github.com/grafana/loki/issues/2881 this is fixed in 2.1.

**Closed** 2021-01-07 16:31 UTC
