### ISSUE TITLE
Adding Loki as a Prometheus data source returns 500 error

### ISSUE THREAD

**Issue by Corbeno** [grafana/loki#5930] opened 2022-04-14 14:25 UTC
**Describe the bug**
When adding Loki a Prometheus data source in Grafana, a 500 error is returned.

**To Reproduce**
1. Started Loki (2.5.0)
2. Started Promtail (2.4.0)
3. Attempt to add a new Prometheus data source with the following url: http://loki:3100/loki

**Expected behavior**
The data source gets added. Instead, a 500 error is returned.

**Environment:**
 - Infrastructure: docker

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/15672485/163410815-71c7efc4-e25b-421b-bde3-aacc9a59ae28.png)
![image](https://user-images.githubusercontent.com/15672485/163411071-f607cb76-5e91-4788-9fb6-a2aa93e6a4bc.png)

**Comment by dannykopping** [comment] 2022-04-14 14:28
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Closed by dannykopping** 2022-04-14 14:28 UTC

**Comment by Corbeno** [comment] 2022-04-14 15:03
I'm confused why you might think this is a question/support request. A 500 error is a service error, and this configuration used to work in previous versions.

**Comment by dannykopping** [comment] 2022-04-14 15:17
@Corbeno you did not specify that it used to work in previous versions in the issue report.

The issue is quite light on details. Please provide additional details like error logs from your Loki server. The errors should indicate what the problem is.

We get questions like this from time to time, and they're generally not bugs but rather small configuration issues, which we prefer to assist with on Slack/forums instead of an issue since it's generally not an issue with the software.

**Comment by Corbeno** [comment] 2022-04-14 15:25
You are correct that it is light on details. I'm working on combing through the loki logs, but I haven't been able to find anything yet. 

This feature seemed odd to me anyway. @dannykopping are you aware if this is supported/intended still? Or is there a better way to get a Loki alert compatible data source into grafana?

**Comment by Corbeno** [comment] 2022-04-14 15:28
Here are the only logs I was able to find in Loki
![image](https://user-images.githubusercontent.com/15672485/163423042-f007596e-c84b-4731-b27f-2c220a274c04.png)

**Comment by dannykopping** [comment] 2022-04-14 19:52
Reach out to us on Slack or the forums, would you? I see no indication of a bug here, but rather a mismatched expectation and/or a usage question.

We're very happy to help, and we want you to have the best experience possible with our product, but GitHub Issues is for bugs & feature requests only. It's not a great medium for a fluid back and forth.
