### ISSUE TITLE
Loki keeps crashing with an error message "failed services"

### ISSUE THREAD

**Issue by Anusha-Kolli** [grafana/loki#6382] opened 2022-06-13 18:21 UTC
**Describe the bug**
Loki pod keeps crashing with caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:402\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"

**To Reproduce**
1. Started Loki  2.4.2
2. Started Promtail (SHA or version) to tail '2.4.2'
3. Query: `{} term`

**Expected behavior**
Loki pod should run continuously instead Loki pod failing liveness and readiness

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2022-06-13T16:24:36.774698739Z caller=compactor.go:287 msg="compactor exiting"
level=info ts=2022-06-13T16:24:36.77471814Z caller=basic_lifecycler.go:197 msg="ring lifecycler is shutting down" ring=compactor
level=info ts=2022-06-13T16:24:36.774696638Z caller=lifecycler.go:466 msg="lifecycler loop() exited gracefully" ring=distributor
level=error ts=2022-06-13T16:24:36.77471034Z caller=loki.go:367 msg="module failed" module=ingester error="context canceled"
level=info ts=2022-06-13T16:24:36.774750343Z caller=lifecycler.go:777 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=distributor
level=info ts=2022-06-13T16:24:36.774906157Z caller=lifecycler.go:518 msg="instance removed from the KV store" ring=distributor
level=info ts=2022-06-13T16:24:36.774942761Z caller=module_service.go:96 msg="module stopped" module=distributor
level=info ts=2022-06-13T16:24:36.774940961Z caller=basic_lifecycler.go:363 msg="unregistering instance from ring" ring=compactor
level=info ts=2022-06-13T16:24:36.774953562Z caller=module_service.go:96 msg="module stopped" module=query-frontend
level=info ts=2022-06-13T16:24:36.774996766Z caller=module_service.go:96 msg="module stopped" module=query-frontend-tripperware
level=info ts=2022-06-13T16:24:36.775008967Z caller=basic_lifecycler.go:234 msg="instance removed from the ring" ring=compactor
level=info ts=2022-06-13T16:24:36.77504927Z caller=module_service.go:96 msg="module stopped" module=compactor
level=info ts=2022-06-13T16:24:36.775308094Z caller=module_service.go:96 msg="module stopped" module=querier
level=info ts=2022-06-13T16:24:36.775386401Z caller=basic_lifecycler.go:197 msg="ring lifecycler is shutting down" ring=scheduler
level=info ts=2022-06-13T16:24:36.775437705Z caller=table_manager.go:87 msg="stopping table manager"
level=info ts=2022-06-13T16:24:36.775453707Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2022-06-13T16:24:36.775470408Z caller=basic_lifecycler.go:363 msg="unregistering instance from ring" ring=scheduler
level=info ts=2022-06-13T16:24:36.775388701Z caller=module_service.go:96 msg="module stopped" module=ingester-querier
level=info ts=2022-06-13T16:24:36.775496511Z caller=basic_lifecycler.go:234 msg="instance removed from the ring" ring=scheduler
level=info ts=2022-06-13T16:24:36.775526313Z caller=module_service.go:96 msg="module stopped" module=query-scheduler
level=info ts=2022-06-13T16:24:36.775552416Z caller=table.go:335 msg="uploading table index_19156"
level=info ts=2022-06-13T16:24:36.828100961Z caller=table.go:362 msg="finished uploading table index_19156"
level=info ts=2022-06-13T16:24:36.828149465Z caller=table.go:420 msg="cleaning up unwanted dbs from table index_19156"
level=info ts=2022-06-13T16:24:36.833788175Z caller=module_service.go:96 msg="module stopped" module=store
level=info ts=2022-06-13T16:24:37.187592625Z caller=module_service.go:96 msg="module stopped" module=ring
level=info ts=2022-06-13T16:24:37.187719836Z caller=module_service.go:96 msg="module stopped" module=memberlist-kv
level=info ts=2022-06-13T16:24:37.189779422Z caller=server_service.go:50 msg="server stopped"
level=info ts=2022-06-13T16:24:37.189819526Z caller=module_service.go:96 msg="module stopped" module=server
level=info ts=2022-06-13T16:24:37.189835927Z caller=loki.go:356 msg="Loki stopped"
level=error ts=2022-06-13T16:24:37.189928236Z caller=log.go:106 msg="error running loki" err="failed services\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:402\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"

Any help would be appreciated

**Comment by DylanGuedes** [comment] 2022-06-13 18:28
Do you mind sharing the whole log (or at least the messages that appear before the EXITED message)? I think it will help to find the issue.

**Comment by DylanGuedes** [comment] 2022-06-13 18:32
Do you mind setting log-level=debug?

**Comment by Anusha-Kolli** [comment] 2022-06-13 18:35
I can see from kubernetes events pod is failing liveness and getting status code 503.

**Comment by DylanGuedes** [comment] 2022-06-13 18:40
```
caller=flush.go:221
org_id=fake msg="failed to flush user" err="write error: ->
github.com/Azure/azure-pipeline-go/pipeline.NewError, /src/loki/
vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:157\nHTTP
request failed\n\nPut \"https://
dap0prod0std0loki.blob.core.windows.net/loki/fake/
67fb30b3e3a74df8-1815d85c53d-1815d8618e2-c49867f8?
blockid=YlCNBpbeQUeiXeQMDgJZfgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&comp=block&timeout=1\": context
deadline exceeded\n"
```
My hypothesis is that something is not right with your Azure/storage setup. The rest looks good, though.

**Comment by Anusha-Kolli** [comment] 2022-06-13 18:44
This setup is running without any issues from last 2 years with timely upgrades. not sure why we are seeing this issue from last one week

**Comment by dannykopping** [comment] 2022-06-13 18:55
I agree with @DylanGuedes - this appears to be an issue with your object storage, and not Loki.
I would suggest opening a support ticket with Azure, or examining your egress network activity to ensure you don't have any saturation that might cause timeouts (which is what `context deadline exceeded` is referring to).

Closing this for now as it's not a bug, as we try keep GH Issues for bugs/features only.
If you need further assistance, reach out to use using one of the following channels:

  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**Closed by dannykopping** 2022-06-13 18:55 UTC
