### ISSUE TITLE
[Cassandra] Loki is unable to reconnect to the Cassandra-Cluster if the IP-Adresses have changed

### ISSUE THREAD

**Issue by Espe0n** [grafana/loki#7140] opened 2022-09-13 09:05 UTC
**Describe the bug**
Hello Everybody

The Issue happens when Loki is set up with Cassandra and occurs when the IP-Address of the Cassandra-Cluster has changed for some reason (f.e.: When the Cassanda-Pods are rescheduled to another Node)
The Loki instances then stop posting Data to the Cassandra-Cluster and instead of requesting the new IP-Addresses remain in a NodeDown NodeUp loop

```
│ loki level=info ts=<redacted> caller=events.go:247 module=gocql client=chunks-write msg=Session.handleNodeUp ip=x.x.x.13 port=9042                │
│ loki level=info ts=<redacted> caller=events.go:271 module=gocql client=chunks-write msg=Session.handleNodeDown ip=x.x.x.53 port=9042              │
│ loki level=info ts=<redacted> caller=events.go:247 module=gocql client=chunks-write msg=Session.handleNodeUp ip=x.x.x.53 port=9042                │
│ loki level=info ts=<redacted> caller=events.go:271 module=gocql client=chunks-write msg=Session.handleNodeDown ip=x.x.x.13 port=9042              │
│ loki level=info ts=<redacted> caller=events.go:271 module=gocql client=chunks-write msg=Session.handleNodeDown ip=x.x.x.53 port=9042              │
│ loki level=info ts=<redacted> caller=events.go:247 module=gocql client=chunks-write msg=Session.handleNodeUp ip=x.x.x.92 port=9042                │
│ loki level=info ts=<redacted> caller=events.go:247 module=gocql client=chunks-write msg=Session.handleNodeUp ip=x.x.x.53 port=9042                │
│ loki level=info ts=<redacted> caller=events.go:271 module=gocql client=chunks-write msg=Session.handleNodeDown ip=x.x.x.92 port=9042              │
│ loki level=info ts=<redacted> caller=events.go:271 module=gocql client=chunks-write msg=Session.handleNodeDown ip=x.x.x.53 port=9042              │
│ loki level=info ts=<redacted> caller=events.go:247 module=gocql client=chunks-write msg=Session.handleNodeUp ip=x.x.x.92 port=9042                │
│ loki level=info ts=<redacted> caller=events.go:247 module=gocql client=chunks-write msg=Session.handleNodeUp ip=x.x.x.13 port=9042                │
│ loki level=info ts=<redacted> caller=events.go:271 module=gocql client=chunks-write msg=Session.handleNodeDown ip=x.x.x.92 port=9042              │
│ loki level=info ts=<redacted> caller=events.go:247 module=gocql client=chunks-write msg=Session.handleNodeUp ip=x.x.x.53 port=9042                │
```

The Issue is in the GOCQL-Library and has been fixed here some time ago
https://github.com/gocql/gocql/commit/312a614907c8d2e19f6b14aff16015436cb78423 (Fix reconnecting to cluster)
https://github.com/gocql/gocql/commit/64cda7bcf8de3792b216753f4883105865b0fa56 (Identify nodes by their host_id instead broadcasted_address)

These fixes are missing in the Fork Loki uses https://github.com/grafana/gocql (last update 2 years ago!)

Is the Fork really required / Is it possible to switch back to the original Library?
Otherwhise it is required to Cherry-Pick at least these two commits to this Repo (https://github.com/grafana/gocql ) in order to fix the Issue 

**To Reproduce**
1. Started Loki (2.6.1) together with a Cassandra-Cluster
2. Reschedule the Cassandra PODs to a different Node
3. Investigate the Logs of the Loki-Ingester

**Expected behavior**
Loki can use the Service-Name of the Cassandra-Cluster to retrieve new IP-Adresses in case these have changed

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Comment by liguozhong** [comment] 2022-09-13 11:51
It turns out that I will also encounter the unavailability of loki caused by the cassandra ip change.
 I implemented the ‘reconnect cassandra client’ in my loki git branch. This feature has been running for 4 months. 
This PR helps my loki avoid cassandra`s Unavailability problems caused by IP changes.
But now loki is ready to delete the code of the cassandra index module, I'm not sure if this PR will be merged.
If you have your own loki branch code, you can try adding the reconnect feature, which can help you avoid this problem

https://github.com/grafana/loki/pull/6725

**Comment by Espe0n** [comment] 2022-09-13 14:28
Hi @liguozhong ,

first, thank you for sharing your PR

liguozhong> *This PR helps my loki avoid cassandra`s Unavailability problems caused by IP changes.*

But this is then more a Workaround rather than a Fix?
The Grafana-Version of Gocql will still incorrectly handle the NodeDown-Event, just a new Session will be created in such cases and the “broken” one is closed if succeeded.

liguozhong> *But now loki is ready to delete the code of the cassandra index module, I'm not sure if this PR will be merged.* 

Okay this is sad to hear, since this would mean we lose Cassandra as the all-in-one Solution for Index + Chunkstore
At least so far it seems like it is “only” in discussion (which gives me a bit of hope)

But independent of that, the Issue affects both Cassandra as an Index-Store and as a Chunk-Store (see logs above), which means that the Issue should be still addressed, since Cassandra can be still used as a chunk-store

So again, thank you for sharing, it really helped 😊

**Comment by liguozhong** [comment] 2022-09-15 01:42
Last night, the node evicted the pod, causing the IP address of cassandra to change again, but the PR regained the new IP address, avoiding the unavailability of loki. This PR allows me to sleep at ease without worrying about the change of cassandra IP.

If you want to directly modify the dependency of gocql mod, it will be a huge work. I don't think it is cost-effective, so I complete the ‘connect’ feature on the loki side.

![image](https://user-images.githubusercontent.com/9583245/190293158-c517977f-c733-4b19-a4d8-adcf175073f9.png)

**Comment by liguozhong** [comment] 2022-09-15 09:27
If this problem is not solved,  when the cassandra deployed through k8s, loki will face huge risks

**Comment by liguozhong** [comment] 2022-09-25 02:43
ref isuue:
https://github.com/yugabyte/yugabyte-db/issues/10182
https://github.com/gocql/gocql/issues/1575

**Comment by liguozhong** [comment] 2022-09-25 03:12
`replace github.com/gocql/gocql => github.com/gocql/gocql v1.2.1
`

I've tried upgrading gocql to the latest version, but I still can't solve this for loki.

![image](https://user-images.githubusercontent.com/9583245/192126527-6923c1af-f704-4dce-adb8-ddff5190fb9f.png)

**Closed** 2024-02-26 19:13 UTC
