### ISSUE TITLE
Loki frontend returns duplicates

### ISSUE THREAD

**Issue by germetist** [grafana/loki#6929] opened 2022-08-17 12:31 UTC
**Describe the bug**
Loki frontend returns 16x duplicates when using filter by string

**To Reproduce**
1. Clone repo from current main https://github.com/grafana/loki/commit/965650740cb54d6a2cc5ee2f931ea01af44ac48e
2. Go to [production/docker](https://github.com/grafana/loki/tree/main/production/docker/) folder
3. Started Loki from [docker-compose.yaml](https://github.com/grafana/loki/blob/main/production/docker/docker-compose.yaml)
4. Open [grafana ](http://127.0.0.1:3000/explore?orgId=1&left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bfilename%3D%5C%22%2Fvar%2Flog%2Fgenerated-logs.txt%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)
5. Filter logs by string

**Expected behavior**
Return logs without duplicates

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**
![chrome_O0iK0cEo1v](https://user-images.githubusercontent.com/4971258/185121570-83d77135-3ede-4eca-bfe4-ae02e9941c87.jpg)
![chrome_QD8NztqyGp](https://user-images.githubusercontent.com/4971258/185121611-8e96d53f-e456-48cf-9b77-f52c8870da19.jpg)

**Comment by DylanGuedes** [comment] 2022-08-17 12:35
I'll try to replicate this. Which version are you using?

**Comment by germetist** [comment] 2022-08-17 12:37
> I'll try to replicate this. Which version are you using?

i just clone current master 965650740

**Comment by DylanGuedes** [comment] 2022-08-17 12:58
I quickly built a new Loki binary using that version, sent replicated logs, and couldn't replicate this (running in monolithic mode). So it might be an edge case :thinking:

**Comment by DylanGuedes** [comment] 2022-08-17 13:09
double checking, can you confirm that the **complete timestamps** are exactly the same? (in nanoseconds)

**Comment by germetist** [comment] 2022-08-17 13:15
> double checking, can you confirm that the **complete timestamps** are exactly the same? (in nanoseconds)

yep, absolutly the same
![chrome_3AXx8mnwK3](https://user-images.githubusercontent.com/4971258/185143553-0e106e66-2a17-4f93-a8ee-743edb4e9a61.jpg)

**Comment by germetist** [comment] 2022-08-18 10:00
Easiest way to reproduce

1. Clone repo from current main 25e8365d0
2. Go to [production/docker](https://github.com/grafana/loki/tree/main/production/docker/) folder
3. `docker compose up -d`
4. `curl -s -H 'X-Scope-OrgID:Tenant1' -H "Content-Type: application/json" -XPOST -s "http://localhost:8080/loki/api/v1/push" --data-raw '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ '\"$(date +%s%N)\"', "fizzbuzz" ] ] }]}'`
5. `curl -G -s -H 'X-Scope-OrgID:Tenant1' "http://localhost:8080/loki/api/v1/query_range" --data-urlencode 'query={foo="bar2"}' --data-urlencode 'step=300' | jq`
6. `curl -G -s -H 'X-Scope-OrgID:Tenant1' "http://localhost:8080/loki/api/v1/query_range" --data-urlencode 'query={foo="bar2"}|= `fizzbuzz`' --data-urlencode 'step=300' | jq`

And we see `data.result.values` 16x times with the same timestamp
```
{
  "status": "success",
  "data": {
    "resultType": "streams",
    "result": [
      {
        "stream": {
          "foo": "bar2"
        },
        "values": [
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ],
          [
            "1660816430487235740",
            "fizzbuzz"
          ]
        ]
      }
    ],
    "stats": {
      "summary": {
        "bytesProcessedPerSecond": 1041,
        "linesProcessedPerSecond": 130,
        "totalBytesProcessed": 256,
        "totalLinesProcessed": 32,
        "execTime": 0.245710213,
        "queueTime": 50.676309619,
        "subqueries": 5,
        "totalEntriesReturned": 16
      },
      "querier": {
        "store": {
          "totalChunksRef": 0,
          "totalChunksDownloaded": 0,
          "chunksDownloadTime": 0,
          "chunk": {
            "headChunkBytes": 0,
            "headChunkLines": 0,
            "decompressedBytes": 0,
            "decompressedLines": 0,
            "compressedBytes": 0,
            "totalDuplicates": 16
          }
        }
      },
      "ingester": {
        "totalReached": 2736,
        "totalChunksMatched": 32,
        "totalBatches": 32,
        "totalLinesSent": 32,
        "store": {
          "totalChunksRef": 0,
          "totalChunksDownloaded": 0,
          "chunksDownloadTime": 0,
          "chunk": {
            "headChunkBytes": 256,
            "headChunkLines": 32,
            "decompressedBytes": 0,
            "decompressedLines": 0,
            "compressedBytes": 0,
            "totalDuplicates": 0
          }
        }
      }
    }
  }
}
```

**Comment by germetist** [comment] 2022-08-18 10:08
This behavior since 305936a861c2c9a957649a6cf128930c8c51ef2b by https://github.com/grafana/loki/pull/6691

**Comment by DylanGuedes** [comment] 2022-08-18 10:17
Thanks, no idea why it didn't show up when I tested on https://github.com/grafana/loki/issues/6929#issuecomment-1217976985 but I could easily reproduce it with this setup that you shared. I'll be investigating it today, ty.

**Comment by DylanGuedes** [comment] 2022-08-19 14:39
I managed to reproduce issues (not exactly the one you saw) regardless of running with SSD or monolithic, just as long as I was querying a frontend with a filter in the query.

**Comment by gpay-tungnd** [comment] 2022-09-06 05:09
same issue with @germetist 
![image](https://user-images.githubusercontent.com/110236181/188551493-da07bd76-fc41-4d7d-92b0-69f40e8f6922.png)

**Comment by 17billion** [comment] 2022-09-22 23:00
Same issue occurs. Are there any updates? @DylanGuedes 
Loki ver : 2.5.0
![스크린샷 2022-09-23 오전 7 53 35](https://user-images.githubusercontent.com/28832461/191865896-2dae2834-9353-42ff-b7ee-e2ab5f11874a.png)

**Comment by DylanGuedes** [comment] 2022-09-22 23:24
Nope, sorry :(
I had to drop this investigation to look for other issues. It is in my radar, though.

**Comment by hejiazhen1203** [comment] 2022-09-23 10:37
@DylanGuedes i has the same issue, use the **Simple scalable deployment mode** , when use filter query , frontend will return 16x lines。
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/22071818/191943393-c7209d53-7ebc-4834-892c-b310c88e628b.png">

**Comment by DylanGuedes** [comment] 2022-09-23 11:35
I wrote a functional test intended to replicate the issue but unfortunately, it didn't. In case you folks are curious:
https://github.com/grafana/loki/pull/7232/files

**Comment by DylanGuedes** [comment] 2022-09-23 11:49
@hejiazhen1203 What is your split-queries-by-range config?

**Comment by hejiazhen1203** [comment] 2022-09-23 13:17
This is my config @DylanGuedes , when i set  query_range.parallelise_shardable_queries to  false that frontend will rerturn correct. but i don't know why?
```yaml
---
auth_enabled: false

analytics:
  reporting_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
  grpc_server_max_recv_msg_size: 16777216
  grpc_server_max_send_msg_size: 16777216

memberlist:
  join_members:
    - loki-read
    - loki-write
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

common:
  replication_factor: 1
  storage:
    s3:
      endpoint: 
      insecure: true
      bucketnames: loki
      access_key_id: 
      secret_access_key: 
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist

schema_config:
  configs:
  - from: 2022-09-15
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

ingester:
  wal:
    enabled: true
    dir: /loki/wal
    flush_on_shutdown: true
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  max_chunk_age: 60m
  chunk_idle_period: 30m
  chunk_retain_period: 30m
  chunk_encoding: snappy
  chunk_target_size: 8388608
  chunk_block_size: 262144
  flush_op_timeout: 10s

distributor:
  ring:
    kvstore:
      store: memberlist

storage_config:
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  index_cache_validity: 5m
  index_queries_cache_config:
    enable_fifocache: true
    redis:
      endpoint: 
      password: 
      expiration: 1h
      idle_timeout: 10m

chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
    redis:
      endpoint: 
      password: 
      expiration: 1h
      idle_timeout: 10m
  write_dedupe_cache_config:
    enable_fifocache: true
    redis:
      endpoint: 
      password: 
      expiration: 1h
      idle_timeout: 10m

limits_config:
  split_queries_by_interval: 30m
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_entries_limit_per_query: 20000
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 200
  per_stream_rate_limit: 30MB
  retention_period: 360h

query_range:
  align_queries_with_step: true
  max_retries: 5
  parallelise_shardable_queries: true
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 30m
      redis:
        endpoint: 
        password: 
        expiration: 1h
        idle_timeout: 10m

frontend:
  log_queries_longer_than: 0s
  compress_responses: true
  max_outstanding_per_tenant: 2048

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

querier:
  query_ingesters_within: 2h
  query_timeout: 5m
  tail_max_duration: 1h
  engine:
    timeout: 5m
    max_look_back_period: 30s

```

**Comment by DylanGuedes** [comment] 2022-09-23 13:17
wow that's actually a great find, thank you. I'll now try to replicate it by changing that config.

**Comment by DylanGuedes** [comment] 2022-09-23 13:51
@hejiazhen1203 I tested again (on [this PR](https://github.com/grafana/loki/pull/7232/files)) and unfortunately I couldn't replicate the issue there even with parallelise_shardable_queries=true.

**Comment by hejiazhen1203** [comment] 2022-09-23 13:52
@DylanGuedes is deploy mode is

**Comment by DylanGuedes** [comment] 2022-09-23 15:10
At first I couldn't replicate any issues even with SSD, but by using query-frontend+SSD I could replicate a bug/behavior that is likely linked to the issues you're experiencing.

**Comment by DylanGuedes** [comment] 2022-09-23 15:21
I won't be able to work on a fix soon because I have a lot of other things to work on that have higher priority, but I'll let the PR that replicates the issue shared with you all so in case someone has free time you can try searching for the culprit by using git bisect+rerunning the test that exposes the bug.

**Comment by slim-bean** [comment] 2022-09-23 17:56
@DylanGuedes and I were chatting on the side around this, the problem is this docker compose is running two query-frontends.

The `read` target of Loki includes a query-frontend, therefore you should _not_ run an additional frontend separately.

Effectively queries are being split and sharded twice which is causing all the problems.

Removing the query-frontend from the docker-compose and routing all read traffic to the `read` container should fix the issue.

**Comment by BalzySte** [comment] 2022-11-04 20:23
I'm experiencing the same issue reported by @germetist, exactly 16x duplicated lines when adding a string filter. It really gave me a headache. I'm also deploying the stack from `/production/docker`. As a quickfix I've set `query_range.parallelise_shardable_queries` to `false`.

Reading @slim-bean latest reply seems the problem is in the services architecture. Can I expect a fix anytime soon?
I can probably work on this but I currently lack deep knowledge of Loki architecture. If I have time I'll submit a PR

**Comment by DylanGuedes** [comment] 2022-11-04 22:59
> I'm experiencing the same issue reported by @germetist, exactly 16x duplicated lines when adding a string filter. It really gave me a headache. I'm also deploying the stack from `/production/docker`. As a quickfix I've set `query_range.parallelise_shardable_queries` to `false`.
> 
> Reading @slim-bean latest reply seems the problem is in the services architecture. Can I expect a fix anytime soon? I can probably work on this but I currently lack deep knowledge of Loki architecture. If I have time I'll submit a PR

The problem is the docker-compose setup: the read component of SSD mode already have its own query-frontend. By pointing another query-frontend to a read component we're prone to these duplications. That said, the problem isn't Loki itself, but the docker-compose that we have available. The solution is removing the query-frontend of that docker-compose manifest.

**Comment by BalzySte** [comment] 2022-12-29 16:22
I've just created a PR https://github.com/grafana/loki/pull/8019 that fixes this issue, tested on the logging infrastructure I'm currently maintaining.  
Feel free to check it out and merge it if it's appropriate.

**Comment by DylanGuedes** [comment] 2023-01-30 18:07
Closing the issue as a recent change fixed the SSD configuration example to not use query-frontend.

**Closed by DylanGuedes** 2023-01-30 18:07 UTC
Labels: kind/bug, component/query-frontend
