### ISSUE TITLE
Missing log lines when using json parser and label filter on a loki data source 

### ISSUE THREAD

**Issue by wallrj** [grafana/loki#3345] opened 2021-02-02 08:15 UTC
I (sometimes) notice that when I add a *matching* filter to a loki log query, matching log lines are not shown in the results.
When I remove the filter, all the log lines are shown.

## With filter

![Screenshot_2021-02-02 Checkin and Checkout - Grafana(1)](https://user-images.githubusercontent.com/978965/106600726-b39bfc00-6552-11eb-820d-1d3018d5721b.png)

## Without filter

![Screenshot_2021-02-02 Checkin and Checkout - Grafana](https://user-images.githubusercontent.com/978965/106570590-00211080-652e-11eb-80de-75ce192808af.png)

I expected all three log lines to be shown in both these queries.

I have sometimes noted that simply adding the `json` processor to the pipeline results in log lines missing from the results.

The newest line is the one that remains.

**Environment**:
Grafana Cloud: Grafana v7.3.7 (1e261642f4)

**Comment by ivanahuckova** [comment] 2021-02-16 16:37
@wallrj thanks for sharing this! I have transferred this to `grafana/loki` repo as it seems like a problem on Loki side and not Grafana.

**Comment by cyriltovena** [comment] 2021-02-16 17:34
Hey @wallrj,

Do you see this issue for anything else than fresh data ? Or this mostly happening when querying recent data ? Can reproduce this over and over ?

Trying to gather more information to pinpoint the issue.

**Comment by wallrj** [comment] 2021-02-16 20:29
Hi @cyriltovena 

Thanks for investigating.

> Do you see this issue for anything else than fresh data ? Or this mostly happening when querying recent data ? Can reproduce this over and over ?

It seems to only be when querying recent data. 
When I zoom back in on the three log lines above, between 0645 and 0730 this morning, I now see all  three log lines, even with the `json` filter.

And also worth noting that the three log events showed up in the loki based graphs, even for recent data, and those also use the `json` filter.
I have a dashboard showing: graph (checkin / checkout per hour), graph(checkin duration), and a logs panel showing the log lines. 
It just 
So this morning, when I sent the query inspector output,  

Let me know if you need any other info.

**Comment by cyriltovena** [comment] 2021-02-18 15:14
I'm chasing this one, I think it's a duplicate of #3208.

**Comment by loganmc10** [comment] 2021-02-25 03:29
I think I'm running into a similar issue, I feel like I'm losing my mind. I have JSON data going into Loki, and sometimes when I query it, not all the lines show up. If I fiddle with my selectors, and wait for a bit, it seems to fix itself, and the missing lines reappear.

It seems to be more based on the time than anything, since after they reappear, the original query works.

I'm on Grafana Cloud (7.4.3 currently), it's a very hard thing to pin down, but it's definitely happening

**Comment by cyriltovena** [comment] 2021-02-25 09:09
@loganmc10 @wallrj A fix is on its way, finally found it. Thank you for your patience.

**Closed** 2021-02-26 15:47 UTC
