### ISSUE TITLE
Dynamic prefix with S3

### ISSUE THREAD

**Issue by VishalPhenom** [grafana/loki#5779] opened 2022-04-06 06:22 UTC
Whenever i am using S3 bucket it is storing logs to rood directory only. i am pushing json object with some parameter to loki, want to set prefix path as per variable in json. 

ex. 

default path is : /tmp/loki

my json obj: 
```
{
    "streams":
        [
            {
                "stream":
                {
                    "refNum":"something"
                },
                "values":
                [
                    ["1643323824886697738","Test"]
                ]
            }
        ]
}
```

now as per the above json object prefix should be **/something/loki**, this "something" is refNum in json obj.

**Comment by dannykopping** [comment] 2022-09-28 07:47
Duplicate of #5889

**Closed by dannykopping** 2022-09-28 07:47 UTC
