### ISSUE TITLE
Production setup for Helm chart

### ISSUE THREAD

**Issue by agolomoodysaada** [grafana/loki#601] opened 2019-05-17 15:51 UTC
**Is your feature request related to a problem? Please describe.**
Yes. Today the Loki helm chart has all the components deployed as one pod.

**Describe the solution you'd like**
The helm chart should deploy the production setup (1x distributor, 3x ingester, 3x querier and 1x tablemanager) as their own deployments/statefulsets.

**Comment by Kuqd** [comment] 2019-06-07 15:03
we might want to introduce another chart or a flag to deploy in a microservices way.

I still think have the single process is an interesting option for small workload or people just willing to try out.

There is work on cortex side to support this. That can be helpful


/cc @steven-sheehy

**Comment by steven-sheehy** [comment] 2019-06-07 15:11
Yes, I agree. The chart should support both modes of operation. I believe it should be doable since the loki sub-chart can just be re-used with different args passed to it to startup in different modes (ingester, querier, etc). I just don't have experience running Loki in this manner to do it myself.

Note that #643 and this are duplicates. That issue gives some example yaml on how to deploy separately.

**Comment by Kuqd** [comment] 2019-06-07 18:57
ok let's wait some movement on cortexproject/cortex#1410. Duplicate of #643.

**Closed by Kuqd** 2019-06-07 18:57 UTC
Labels: component/loki, kind/question
