### ISSUE TITLE
Rotated log files promtail error

### ISSUE THREAD

**Issue by fernandovillamaria** [grafana/loki#3985] opened 2021-07-12 17:25 UTC
Hello, I have the following problem and I wanted to know if it is possible to solve it. I found this entry https://github.com/grafana/loki/issues/3108 but I am not clear if it could be fixed or not. I attach logs and promtail settings.

Jul 2 12:37:31 mendieta promtail: level=info ts=2021-07-02T15:37:31.741999535Z caller=tailer.go:173 component=tailer msg=“skipping update of position for a file which does not currently exist”
Jul 2 12:37:32 mendieta promtail: level=info ts=2021-07-02T15:37:32.115303193Z caller=tailer.go:173 component=tailer msg=“skipping update of position for a file which does not currently exist”
Jul 2 12:37:32 mendieta promtail: level=info ts=2021-07-02T15:37:32.358223961Z caller=tailer.go:173 component=tailer msg="skipping update of position for a file which does not currently exist

server:
http_listen_port: 9080
grpc_listen_port: 0

positions:
filename: /tmp/positions.yaml

clients:

url: http://grafana.pert.io:3100/loki/api/v1/push
scrape_configs:

job_name: system
static_configs:
labels:
job: logstashlogs # A job label is fairly standard in prometheus and useful for linking metrics and logs.
host: ${HOSTNAME}
path: /var/log/logstash/log*.log
promtail, version 2.2.1

Regards.

**Comment by Kampe** [comment] 2021-07-15 17:19
we see this happen consistently as well with our promtail instance, same version.

**Comment by hwshea18** [comment] 2021-07-19 13:21
Are there any updates on this issue? We are seeing the same thing

**Comment by cesarmesones** [comment] 2021-09-27 16:50
We are also experiencing this issue, any updates?

**Comment by taintedkernel** [comment] 2021-10-10 04:26
Believe I'm hitting this as well, using the Helm charts for promtail and loki.  I've only noticed this on one particular pod, with the same error "skipping update of position...", then followed by "position timer: exited".

I've tried looking through the config, but I'm still new to loki/promtail and nothing obvious is jumping out to me.

**Comment by yangvipguang** [comment] 2022-03-01 02:21
https://github.com/grafana/loki/issues/3108#issuecomment-1054916428

**Comment by yangvipguang** [comment] 2022-03-01 02:23
@cyriltovena  I have the same issue .
![image](https://user-images.githubusercontent.com/11416887/156091888-53cd0388-7931-46f2-992f-79c6e2473f09.png)
![5EFA29F0-9E89-4226-8013-34F862317560](https://user-images.githubusercontent.com/11416887/156091909-69aa1b7e-7f34-4edf-a3ae-afb4a0d8fed6.png)

after 18:33:31.887. No logs have been reported, and the promtail logs indicate it is waiting for logs to appear, but Application log output is normal。
![image](https://user-images.githubusercontent.com/11416887/156091968-026e715b-20c5-47aa-86bd-b191227395c9.png)
![image](https://user-images.githubusercontent.com/11416887/156092381-7d5c95c0-6032-492f-bf64-0e77d1a69c45.png)

**Comment by Mario-Hofstaetter** [comment] 2022-05-25 07:28
> I got the same error in log "skipping update of position for a file which does not currently exist" because of abandoned log files under windows (romtail, version 2.5.0 (branch: HEAD, revision: [2d9d0ee](https://github.com/grafana/loki/commit/2d9d0ee236ea302950fcf21edc53d53050a3fbbb)))

I can confirm this is regularly an issue with promtail 2.5.0 on windows.

**Comment by iris-xie** [comment] 2022-06-15 01:59
we have the same issue here, indeed the file are renamed by other application.

**Comment by erewok** [comment] 2022-07-06 15:39
We are seeing this on two promtail pods (out of ten) on one of our clusters and those 2 promtail pods also have really high CPU usage (compared to other promtail pods and to what we'd expect). Does anyone else seeing this issue see any correlation with CPU usage?

**Comment by erewok** [comment] 2022-08-09 19:17
Today I updated our Promtail pods to version `2.6.1` using the latest version of the Helm chart and looked again at this issue. 

While looking at our logs, I noticed our `loki-write` pods (in a statefulset) were getting overloaded by requests from the promtail clients. It turns out I had too few `loki-write` nodes, so I scaled up the statefulset. After that, so far this morning both Loki-write and Promtail look to be performing better. 

I have a guess (a complete shot in the dark, so take it for its worth), that our promtail pods were not proceeding because there weren't enough loki-write nodes and that may be why our Promtail-pod CPU usage was high and also why were seeing these log messages repeated for long stretches. 

Now that our Loki pods are looking more healthy, I see the log messages discussed here whenever a pod terminates followed by:

```
level=info ts=2022-08-09T18:31:04.293828288Z caller=filetarget.go:161 msg="filetarget: watcher closed, tailer stopped, positions saved" path=/var/log/pods/*c81337cd-312b-4d45-a759-eb10775c843b/linkerd-proxy/*.log
level=info ts=2022-08-09T18:31:04.293801388Z caller=tailer.go:240 component=tailer msg="stopped tailing file" path=/var/log/pods/finwise_finwise-celery-7cf9d46c9d-sj5nr_c81337cd-312b-4d45-a759-eb10775c843b/linkerd-proxy/0.log
level=info ts=2022-08-09T18:31:04.293778888Z caller=tailer.go:152 component=tailer msg="tail routine: exited" path=/var/log/pods/finwise_finwise-celery-7cf9d46c9d-sj5nr_c81337cd-312b-4d45-a759-eb10775c843b/linkerd-proxy/0.log
level=info ts=2022-08-09T18:31:04.293758088Z caller=tailer.go:159 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=/var/log/pods/finwise_finwise-celery-7cf9d46c9d-sj5nr_c81337cd-312b-4d45-a759-eb10775c843b/linkerd-proxy/0.log reason=null
```

I will keep looking at it. Apologies for the uninformed conjecture but I figured it may be worthwhile to someone?

**Comment by michaelkebe** [comment] 2022-11-08 10:44
@kavirajk Any progress on this. Still happens in out setup.

**Comment by daper** [comment] 2022-12-14 12:02
Here also on EKS with linux nodes. And the agent stops sending new logs when this happens. It must be forcibly terminated in order for a new pod to get re-scheduled.

**Comment by zq-david-wang** [comment] 2022-12-20 07:45
I am using 2.7.0,  sometimes when log file removed and then recreated, promtail would stuck and no log read afterward.

Promtail log shows following sequence:
```
ts=2022-12-20T06:39:51.126377231Z caller=log.go:168 level=info msg="Waiting for ****.log to appear..."
...
level=info ts=2022-12-20T06:39:53.846332941Z caller=filetargetmanager.go:175 msg="received file watcher event" name=****.log op=CREATE

```

feel unbelievable to find this code used by promtail when I tried to dig into
https://github.com/grafana/loki/blob/88f04beb4ef39fa57db20ea21d546fe0a2675fb8/vendor/github.com/grafana/tail/tail.go#L254-L268

The retry counter never count down to zero....

**Comment by zq-david-wang** [comment] 2022-12-21 09:51
After fix the silly retry countdown bug,  following logs show up
```
Dec 21 06:00:22 iZuf6h6buntpmoj3kqqdrgZ promtail[17833]: level=info ts=2022-12-20T22:00:22.259371564Z caller=tailer.go:159 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=****.log reason="gave up trying to reopen log file with a different handle"
Dec 21 06:00:22 iZuf6h6buntpmoj3kqqdrgZ promtail[17833]: level=info ts=2022-12-20T22:00:22.383426439Z caller=tailer.go:159 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=****.log reason="gave up trying to reopen log file with a different handle"
```
Meaning that somehow promtail could be stuck in loop without the fix and the countdown/timeout is necessary for promtail to give up and retry.
I have run with the fixed code for more than 24h,  with log file delete/recreate several times, every log steams seam ok .

**Comment by natalya-onramp** [comment] 2023-05-10 13:39
@kavirajk any chance you could help fixing this - getting https://github.com/grafana/tail/pull/16 to merge?

**Comment by thampiotr** [comment] 2023-05-23 09:15
https://github.com/grafana/tail/pull/16 solved some failure modes in this code, but there is also an unrelated goroutine leak, which is addressed by https://github.com/grafana/loki/pull/9495. Please let us know if you are still experiencing the issues after these fixes.

**Comment by cstyan** [comment] 2023-11-08 01:40
is this still a problem? sounds like the PRs @thampiotr mentioned fixed it?

**Comment by thampiotr** [comment] 2023-11-13 12:10
The fixes above have resolved the same symptoms in our internal cluster, so I believe it can be closed.

**Closed by thampiotr** 2023-11-13 12:10 UTC
Labels: keepalive

**Comment by Upanshu11** [comment] 2024-01-12 19:00
Hello, I am facing same issue in grafana agent v0.36.2 as well.
I am using grafana agent in Kubernetes AKS.
