### ISSUE TITLE
After upgrading to 2.7 multi tenant queries fails

### ISSUE THREAD

**Issue by acukan** [grafana/loki#7696] opened 2022-11-15 10:19 UTC
**Describe the bug**
After upgrading to 2.7 multi tenant queries fails.

It seems we encounter this bug because of this function only checks if query has single tenant id for per tenant override for timeout parameter. 
https://github.com/grafana/loki/blob/v2.7.0/pkg/querier/http.go#L486

**To Reproduce**
Query loki querier with multiple X-Scope-OrgID header

exp:  `curl --location -g --request GET 'localhost:3100/loki/api/v1/query_range?query={namespace=~"loki",_cluster="cluster"}' \
--header 'X-Scope-OrgID: tenant1|tenant2'`
returns: `multiple org IDs present`

**Expected behavior**
It should return query range response

**Comment by akshaykrjain** [comment] 2023-01-12 14:23
Facing the same with `logcli` as well

```sh
logcli series --analyze-labels '{}' --org-id 'tenant1|tenant2'
2023/01/12 15:21:04 https://loki.awesome.com/loki/api/v1/series?end=1673533264335351000&match=%7B%7D&start=1673529664335351000
2023/01/12 15:21:04 Error response from server: multiple org IDs present
 (<nil>) attempts remaining: 0
2023/01/12 15:21:04 Error doing request: Run out of attempts while querying the server; response: multiple org IDs present
```

**Comment by DylanGuedes** [comment] 2023-01-12 16:08
2.7.1 has this fixed.

**Comment by akshaykrjain** [comment] 2023-01-12 16:36
2.8.1

**Comment by pschulten** [comment] 2023-01-12 20:33
I still have the issue with `docker.io/grafana/loki:2.7.1` (I don't think there's a 2.8.1 version...)

**Comment by DylanGuedes** [comment] 2023-01-12 21:43
yes unfortunately 2.7.1 still has it :(
you can try running a weekly that contains the fix (like k131)

**Comment by akshaykrjain** [comment] 2023-01-13 18:04
Sorry, @pschulten @DylanGuedes  It was a typo. I mean `2.7.1`

**Comment by clementguillot** [comment] 2023-01-16 14:08
Any update regarding this issue? We had to downgrade to `2.6.1`, otherwise, we can't query Loki using Grafana and multi-tenants.

**Comment by DylanGuedes** [comment] 2023-01-16 14:23
> Any update regarding this issue? We had to downgrade to `2.6.1`, otherwise, we can't query Loki using Grafana and multi-tenants.

The issue is fixed in the main branchh, it is a matter of releasing a 2.7.2 with a fix. Until it happens I recommend you folks to use 2.6.1 or a weekly that contains the fix (ex: k131).

**Comment by DylanGuedes** [comment] 2023-01-27 19:42
Hey Loki 2.7.2 was released yesterday with a fix to multitenant querying. I'm closing it for now if you don't mind.

**Closed by DylanGuedes** 2023-01-27 19:42 UTC
