### ISSUE TITLE
Promtail to have WAL type system to resume logs

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/loki#3770] opened 2021-05-27 09:53 UTC
When using Promtail (eg on a laptop, IoT device), it is possible for a user to move out of WiFi/internet range and then later on switch off the laptop for the night. When the user switches on again the next day, promtail will be confused as to the true location of which logs to send. Promtail will try to (re)send from the **last_read** position, however due to the wifi off and system shutdown, the true last position is actually further back in the log. Ideally it would be nice if Promtail can send from **last_sent** position. 

For this, Promtail would need to have a type of WAL system, where promtail can maintain a **last_read** position from the source log file, but then write to a WAL file where a **last_sent** position can be maintained for logs that was truly written to Loki successfully or not. 

**Describe the solution you'd like**
Separating last_read and last_sent positioning. Promtail might be able to maintain a last_read position on a log file, but not able to write it to Loki due to Wifi/Internet being down. As described above, if Promtail can maintain a separate positioning system around last_sent (through a WAL file?), then this should resolve the issue. 

This type of use case is common for locations where Wifi/Internet comes and goes. IoT style use cases comes to mind. 

**Describe alternatives you've considered**
FluentBit seems to have a nice way to handle back-pressure and data buffering for data streams. 
(https://docs.fluentbit.io/manual/)

**Comment by slim-bean** [comment] 2021-05-27 11:51
Closing this as a duplicate or near duplicate of #1540 as there is already some discussion on that item around this issue.

**Closed by slim-bean** 2021-05-27 11:51 UTC
