### ISSUE TITLE
Loki Distributor keeps on to get empty ring message with HTTP error 500 

### ISSUE THREAD

**Issue by reidlai** [grafana/loki#4985] opened 2021-12-21 12:47 UTC
I have deployed loki-distributed helm in my Kubernetes Cluster and I also have a fluentbit daemonset running using loki output plugin to feed logs into loki distributor.  But whenever fluentbit call Loki api to write logs, it keeps on encountering empty ring error message with HTTP error 500.  If I switch back loki chart, everything works fine

Here is my Loki config and Fluentbit Output Config:

Fluentbit config:
                    [OUTPUT]
                        Name loki
                        Match *
                        Host loki-distributed-distributor
                        Port 3100
                        Labels job=fluentbit $sub['stream']
                        Auto_Kubernetes_Labels on
                        Retry_Limit 20

Loki Distributor and memberlist config:

              auth_enabled: false
              server:
                http_listen_port: 3100 

              distributor:
                ring:
                  kvstore:
                    store: memberlist

              memberlist:
                abort_if_cluster_join_fails: false
                bind_port: 7946
                join_members:
                  - loki-distributed-memberlist:7946
                max_join_backoff: 1m
                max_join_retries: 10
                min_join_backoff: 1s

              ingester:
                chunk_idle_period: 3m
                chunk_block_size: 262144
                chunk_retain_period: 1m
                max_transfer_retries: 0
                wal:
                  dir: /var/loki/wal
                lifecycler:
                  ring:
                    kvstore:
                      store: inmemory
                    replication_factor: 1

**Comment by DylanGuedes** [comment] 2021-12-21 12:58
I'm not sure if that's the root cause but I find it weird that your distributor is using `memberlist` store while the ingester is using `inmemory`. Shouldn't you be using memberlist for both?

**Comment by trevorwhitney** [comment] 2021-12-21 19:11
Yeah, I think @DylanGuedes has the right idea. Using an `inmemory` kvstore for the ingesters would mean the distributors would never be able to find them, so the ring would indeed be empty. Picking one ring kvstore type and using it across all rings is definitely recommended.

**Comment by reidlai** [comment] 2021-12-22 01:02
oh...sorry...u are right.  let me review and check it.  Thanks guys

**Comment by reidlai** [comment] 2021-12-22 01:02
yeah...sounds like it's my typo

**Comment by DylanGuedes** [comment] 2021-12-27 12:57
Hey I'm closing this one since it worked for you. If you encounter any new issues feel free to open a new one.

**Closed** 2021-12-27 12:57 UTC
