### ISSUE TITLE
Make package Go Module compatible

### ISSUE THREAD

**Issue by lukasmalkmus** [grafana/loki#4359] opened 2021-09-21 09:07 UTC
**Is your feature request related to a problem? Please describe.**

The package is not Go Module compatible. The last version that is "go get-able" is `v1.6.1`:

```shell
$ go get github.com/grafana/loki@v2.3.0
go get: github.com/grafana/loki@v2.3.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Describe the solution you'd like**

Make the package Go Module compatible.

**Describe alternatives you've considered**

There are no proper alternatives apart from maintaining a fork.

**Additional context**

<img width="566" alt="Screenshot 2021-09-21 at 11 06 48" src="https://user-images.githubusercontent.com/9931588/134143757-64598152-624a-4410-9b97-c0b40c167167.png">

**Comment by jeschkies** [comment] 2022-03-03 10:07
This requires changing the version in `go.mod`, right? Could you propose this in a PR? This would trigger a discussion.

**Comment by kavirajk** [comment] 2022-03-18 11:23
Duplicate of #2826. Closing it. Feel free to discuss it in the original issue.

**Closed by kavirajk** 2022-03-18 11:23 UTC
