### ISSUE TITLE
Possible bug in Dockerfile in clients/cmd/logstash

### ISSUE THREAD

**Issue by RosesAreR3d** [grafana/loki#3916] opened 2021-06-30 08:04 UTC
One line in above mentioned Dockerfile contains path to the folder it is in, preventing it from being built form this folder using docker, according to README file.
The line makes it look like its supposed to be built form the main folder.

**Comment by dannykopping** [comment] 2021-07-02 07:38
Closing, as discussed in the PR: this is not a bug.
Thanks for your efforts here though @RosesAreR3d!

**Closed by dannykopping** 2021-07-02 07:38 UTC
