### ISSUE TITLE
 promtail metrics custom: bad icrementation

### ISSUE THREAD

**Issue by thedje** [grafana/loki#2229] opened 2020-06-17 08:57 UTC
Hi,
I have a problem with feeding a custom metric with promtail.
I have the following conf :

# cat config.yml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

scrape_configs:
 - job_name: trace_vtom
   static_configs:
   - targets:
      - localhost
     labels:
       job: trace_vtom
       maif_env: D-DEVELOPPEMENT
       __path__: /travail/sys0/vtom/traces/*.log
   pipeline_stages:Protail 
   - regex:
       source: filename
       expression: '/travail/sys0/vtom/traces/(?P<maif_vtom_environnement>.+).log'
   - labels:
       maif_vtom_environnement:
   - regex:
       expression: '^(?P<time>\d{2}:\d{2}:\d{2} \d{2}-\d{2}-\d{4}) .*$'
   - timestamp:
       source: time
       format: '15:04:05 02-01-2006'
       location: 'Europe/Paris'
   - regex:
      expression: (?P<error_message>Le moteur semble ne plus repondre depuis)
   - metrics:
       error_total_vtom:
         type: Counter
         description: "total count of errors"
         source: error_message
         config:
           action: inc
_____________________________________________________________________________________________

When I add a line in a log file, the metric goes up the number of lines matching the character string:
promtail_custom_error_total_vtom{filename="/travail/sys0/vtom/traces/mINDEPT_______21.log",job="trace_vtom",maif_env="D-DEVELOPPEMENT",maif_vtom_environnement="mINDEPT_______21"} 4

Indeed, the character string is present 4 times in the file:
#grep "Le moteur semble ne plus repondre depuis" mINDEPT_______21.log | wc -l
4

On the other hand, when I add a line without the character string, the metric again adds the number of lines:
promtail_custom_error_total_vtom{filename="/travail/sys0/vtom/traces/mINDEPT_______21.log",job="trace_vtom",maif_env="D-DEVELOPPEMENT",maif_vtom_environnement="mINDEPT_______21"} 8

Do you have an explanation for this problem?
Is this a config problem?

Thank you for your reply

**Comment by cyriltovena** [comment] 2020-06-22 11:32
Hello it would be great if you use code snippet for the config and share an example of the log line creating the metrics. 

Thank you.

**Comment by thedje** [comment] 2020-06-22 13:26
Hello,
My configuration is in the message above and below an example of the log line creating the metrics :

09:50:14 16-06-2020 | th-1cc94740 | 01 |      Tengine.c   371 | Le moteur semble ne plus repondre depuis 30 minutes

**Comment by cyriltovena** [comment] 2020-07-03 19:51
> Hello,
> My configuration is in the message above and below an example of the log line creating the metrics :
> 
> 09:50:14 16-06-2020 | th-1cc94740 | 01 | Tengine.c 371 | Le moteur semble ne plus repondre depuis 30 minutes

It's impossible to read YAML indented like this. 

Can you use code block with proper indentation so we can reproduce this ?

**Comment by thedje** [comment] 2020-08-03 14:53
Hello,

Attached is the config.zip file containing the config.yml file

[config.zip](https://github.com/grafana/loki/files/5016694/config.zip)

**Comment by thedje** [comment] 2020-09-07 11:28
Hello,

Any ideas?

**Comment by UniqueTokens** [comment] 2020-10-04 18:55
The regex expression on line 30 of config.yml is incorrect for its intended purpose. Take a look at my regex quickfix: https://regex101.com/r/pzvqpa/1/

**Comment by thedje** [comment] 2020-10-08 06:19
Hi,
I just tested and it works.
Thank you very much for your help.

**Comment by UniqueTokens** [comment] 2020-10-08 06:27
You are welcome! Please close the issue when you're done.

**Closed** 2020-10-08 06:29 UTC
