### ISSUE TITLE
I can't Choose Loki from the list with Grafana 5.4.3

### ISSUE THREAD

**Issue by feiyujinghong** [grafana/loki#225] opened 2019-01-17 09:02 UTC
I can't Choose Loki from the list with Grafana 5.4.3 ,why?

**Comment by feiyujinghong** [comment] 2019-01-17 09:09
Loki DataSource Only for Docker images ?

**Comment by davkal** [comment] 2019-01-17 10:31
Duplicate of #223

**Closed by davkal** 2019-01-17 10:31 UTC
