### ISSUE TITLE
Crash of container when starting in single binary mode

### ISSUE THREAD

**Issue by NexusNull** [grafana/loki#7465] opened 2022-10-19 07:44 UTC
**Describe the bug**
Installing grafana loki with the following command leads to a non working deployment.
I have already tried to install it with different helm values, from [this](https://github.com/grafana/loki/issues/7435) issue, with no luck so far. 
```
helm repo add grafana https://grafana.github.io/helm-charts
helm upgrade --install loki grafana/loki \
 --set "loki.commonConfig.replication_factor=1"\
 --set "loki.storage.type=filesystem" 
```

**To Reproduce**
1. Install the helm chart
2. wait for it to crash
3. it crashes.

**Expected behavior**
I expected it to _not_ crash.

**Environment:**
 - Infrastructure: GKE Cluster, 3 nodes
 - Deployment tool: helm
 - Chart version: 3.2.1
 - Loki version: 2.6.1

**Terminal output**
```
level=error ts=2022-10-19T07:32:04.120459591Z caller=main.go:51 msg="validating config" err="invalid ruler config: invalid ruler store config: invalid Azure Storage config: unsupported Azure blob storage environment: , please select one of: AzureGlobal, AzureChinaCloud, AzureGermanCloud, AzureUSGovernment "
```

**Comment by NexusNull** [comment] 2022-10-19 08:28
It seems to work with version 3.1 of the chart

**Comment by jkroepke** [comment] 2022-10-19 14:25
It seems like that the issue is introduced in https://github.com/grafana/loki/commit/5e134f3b6d33b2f9b485cde7a70f160704eae5ba

**Comment by trevorwhitney** [comment] 2022-10-26 20:11
This is a duplicate of https://github.com/grafana/loki/issues/7267 and should be fixed by https://github.com/grafana/loki/pull/7528. Thanks for reporting :smile:

**Closed by trevorwhitney** 2022-10-26 20:11 UTC
Labels: area/helm
