### ISSUE TITLE
Cancelling query requests

### ISSUE THREAD

**Issue by czterocyty** [grafana/loki#4699] opened 2021-11-08 11:51 UTC
**Describe the bug**
After upgrade from 2.3.0 to 2.4.0 and applying necessary configuration changes, querying of loki stopped working. I see errors on loki side that some warnings regarding grpc at the time of query. Ingestion seems to work.

A diff of config changes:
```
diff --git a/stacks/monitoring/loki2/config.yaml b/stacks/monitoring/loki2/config.yaml
index af5f643..0fd2f57 100644
--- a/stacks/monitoring/loki2/config.yaml
+++ b/stacks/monitoring/loki2/config.yaml
@@ -14,6 +14,9 @@ ingester:
   chunk_idle_period: 5m
   chunk_retain_period: 30s
   max_transfer_retries: 0
+  wal:
+    enabled: true
+    dir: /loki/wal
 
 schema_config:
   configs:
@@ -36,10 +39,20 @@ limits_config:
   enforce_metric_name: false
   reject_old_samples: true
   reject_old_samples_max_age: 168h
+  retention_period: 744h
+
+compactor:
+  retention_enabled: true
 
 chunk_store_config:
   max_look_back_period: 0s
-
-table_manager:
-  retention_deletes_enabled: true
-  retention_period: 744h
+  chunk_cache_config:
+    enable_fifocache: true
+    fifocache:
+      max_size_bytes: 500MB
+query_range:
+  results_cache:
+    cache:
+      enable_fifocache: true
+      fifocache:
+        max_size_bytes: 500MB
```

**To Reproduce**
1. Started Loki (SHA or version): 2.4.0, loki served on HTTP port 3101
2. Query: `{} term` using curl:
```
curl -G -s http://localhost:3101/loki/api/v1/query --data-urlencode 'query=sum(rate({job="Timescale"}[10m])) by (level)' | jq
```
hangs for minutes. Grafana (7.5.9) UI also hangs.
3. Internal /ready shows 200 OK:
```
$ curl http://localhost:3101/ready
ready
```

**Expected behavior**
Query should give some results.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] - loki run as global service on one node in docker swarm
 - Deployment tool: [e.g., helm, jsonnet] - docker-compose

**Screenshots, Promtail config, or terminal output**
Loki output:
```
level=info ts=2021-11-08T11:40:29.412157675Z caller=metrics.go:92 org_id=fake latency=fast query="sum(rate({job=\"Timescale\"}[10m])) by (level)" query_type=metric range_type=instant length=0s step=0s duration=2.977833ms status=200 limit=100 returned_lines=0 throughput=16MB total_bytes=49kB
level=warn ts=2021-11-08T11:40:33.933982953Z caller=pool.go:184 msg="removing frontend failing healthcheck" addr=10.0.0.214:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
level=error ts=2021-11-08T11:40:33.934185555Z caller=scheduler_processor.go:199 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = grpc: the client connection is closing" frontend=10.0.0.214:9095
```

**Comment by DylanGuedes** [comment] 2021-11-08 13:17
Do you mind sharing your loki config? It worked fine for me with the default `cmd/loki/loki-local-config.yaml` file

**Comment by yafanasiev** [comment] 2021-11-08 13:42
We hit the same problem. It looks like the problem is with querier initializing local cache. This is what we have on the latest (2.4.1) Loki running in distributed mode in AWS EKS:
```
level=error ts=2021-11-08T13:31:33.169513843Z caller=log.go:106 msg="error running loki" err="disk quota exceeded\nerror creating index client\ngithub.com/grafana/loki/pkg/storage/chunk/storage.NewStore\n\t/src/loki/pkg/storage/chunk/storage/factory.go:201\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:365\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:106\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

I believe `disk quota` error refers to the AWS EFS (which we use as a volume for cache): https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-fileop-errors.html#diskquotaerror

Is there any way to control the querier behaviour in this case?

**Comment by yafanasiev** [comment] 2021-11-08 14:05
Confirmed - we removed persistent EFS volumes from querier in favor of index gateway and everything works ok now. Can loading chunks to local storage from S3 be throttled to work around this case?

**Comment by DylanGuedes** [comment] 2021-11-08 14:46
@czterocyty I was able to run `curl -G -s http://localhost:3101/loki/api/v1/query --data-urlencode 'query=sum(rate({job="Timescale"}[10m])) by (level)' | jq` with that config (just had to change folders from `/loki/X` to `/tmp/loki/X`.

**Comment by hhromic** [comment] 2021-11-17 12:19
I encountered the same issue on my side while deploying in a Docker Swarm.

The following simple stack file allows to reproduce the problem:
```yaml
version: '3.8'

services:
  loki:
    image: grafana/loki:2.4.1
    command: >-
      -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    volumes:
      - data:/loki
    deploy:
      mode: replicated
      replicas: 1

volumes:
  data: {}
```

Once the above stack is deployed, querying Loki on port 3100 simply hangs:
```
$ docker stack deploy -c test.yaml test
( wait a moment to initialise )
$ curl -s localhost:3100/loki/api/v1/query --data-urlencode 'query=sum(rate({job="some"}[10m])) by (level)'
( hangs forever here)
```

The logs from Loki show:
```
test_loki.1.v2gderw9s732@docker-desktop    | level=error ts=2021-11-17T12:03:52.3898953Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
test_loki.1.v2gderw9s732@docker-desktop    | level=info ts=2021-11-17T12:04:02.3515748Z caller=metrics.go:92 org_id=fake latency=fast query="sum(rate({job=\"some\"}[10m])) by (level)" query_type=metric range_type=instant length=0s step=0s duration=1.7789ms status=200 limit=100 returned_lines=0 throughput=0B total_bytes=0B
test_loki.1.v2gderw9s732@docker-desktop    | level=info ts=2021-11-17T12:04:03.4786111Z caller=table_manager.go:171 msg="uploading tables"
test_loki.1.v2gderw9s732@docker-desktop    | level=warn ts=2021-11-17T12:04:04.659435Z caller=pool.go:184 msg="removing frontend failing healthcheck" addr=10.0.0.6:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
test_loki.1.v2gderw9s732@docker-desktop    | level=error ts=2021-11-17T12:04:04.6597245Z caller=scheduler_processor.go:199 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = grpc: the client connection is closing" frontend=10.0.0.6:9095
```

It seems to me that Loki is incorrectly  using the ingress network address (`10.0.0.6`) instead of `127.0.0.1` or the the private network of the stack itself. In #4682, a solution was to set the service network mode to `host`, which bypasses the ingress network. Note that I don't think changing the network mode of the service to `host` to be a definitive solution as Loki up to version 2.3.0 was working perfectly fine in this scenario.

When running Loki in plain Docker, i.e. `docker run ...` then it all works fine.

**Comment by cassidy3** [comment] 2021-11-22 17:14
We're encountering the same issue here. I know Docker Swarm Mode is not the most common deployment environment, but it would be fantastic to have a Loki config-based solution to this issue added to the "Upgrading" page on the Grafana website. Surely this isn't a difficult fix in the config?

I played around with the ring instance_interface_names options but wasn't able to find a straightforward fix. Does anyone know how we might go about getting this resoled without changing the Docker Swarm Mode networking settings?

**Comment by hhromic** [comment] 2021-11-24 13:42
@cassidy3 @tskomudek thanks for your replies.
I am not very familiar with Loki's configuration (as I use the stock bundled into the Docker image).
Interesting to see that there are indeed configuration options governing the network interfaces to use.

I think, for the case of containers, Loki should just listen to "all" interfaces as networking is normally operated at the orchestrator level (i.e. Swarm or K8s).

I will explore these options too now. Thanks for the pointer!

**Comment by hhromic** [comment] 2021-11-24 14:04
@tskomudek your solution is working like a charm for me here indeed. Great finding!

How did you find the `frontend.address` option? It doesn't seem to be documented at all:
https://github.com/grafana/loki/blob/main/docs/sources/configuration/_index.md#frontend

Given that the default configuration in the `loki` Docker image already contains this:
```yaml
common:
  ring:
    instance_addr: 127.0.0.1
```

I think what you propose makes sense to use in the default image as well.
@owen-d @slim-bean what do you think?  Let us know if you need further testing of any kind.

**Comment by tskomudek** [comment] 2021-11-24 14:45
Hi @hhromic,

there was a hint to "frontend" in the error message

`
level=error ts=2021-11-08T11:40:33.934185555Z caller=scheduler_processor.go:199 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = grpc: the client connection is closing" frontend=10.0.0.214:9095
`

and so i inspected  [http://localhost:3100/config](http://localhost:3100/config) for available options. But you're right, it's missing in the documentation.

**Comment by hhromic** [comment] 2021-11-24 15:03
> and so i inspected http://localhost:3100/config for available options. But you're right, it's missing in the documentation.

Ah, didn't know about that endpoint, brilliant tip for me! Cheers!

**Comment by cassidy3** [comment] 2021-11-24 16:36
@tskomudek your solution is working for me as well, thank you so much.

I like to think I'm fairly experienced with container networking, but this one really stumped me. I guess my mistake was relying on the Loki documentation too heavily over the running-config - the documentation is incorrect in a couple of places (e.g. the compactor section is listed as compactor_config in the docs; that should have been a red flag).

I'm still not sure I 100% understand why on earth the frontend wouldn't listen on all interfaces by default (a local dev box propped up in bridge mode might not work with the current defaults), but I suppose that's policy for the devs to iron out. I feel like a container-based logging DB really shouldn't be too concerned about network segmentation/security, given that aspect *always* being handled at a network fabric layer.

Anyway, thanks again!

**Comment by hhromic** [comment] 2021-11-24 16:46
@trevorwhitney you seem to have recently updated the default [Loki config files](https://github.com/grafana/loki/tree/main/cmd/loki) bundled into the `loki` Docker image.
Any thoughts on the discussion above and if the solution is acceptable in a PR? Thanks!

**Comment by trevorwhitney** [comment] 2021-11-25 14:26
@hhromic I'm taking a few days off for Thanksgiving, but I can take a look on Monday. I want to poke around a bit to make sure I fully understand the problem. Adding the address for the query frontend seems like a good temporary fix, but ideally I'd love to find something more automatic, as my goal, and the motivation around a lot of the work in 2.4, is to get the config required to run Loki as minimal as possible.

**Comment by hhromic** [comment] 2021-11-25 16:10
@trevorwhitney thanks for replying and for looking into this whenever you see fit 👍.

> Adding the address for the query frontend seems like a good temporary fix, but ideally I'd love to find something more automatic, as my goal, and the motivation around a lot of the work in 2.4, is to get the config required to run Loki as minimal as possible.

Yes, fully agree. As I mentioned earlier, and also as @cassidy3 mentioned as well, networking inside containers should be left to the orchestrator mostly and the application should not need to do any specific networking segmentation on its own but instead just listen on all interfaces by default.

Anyway, take your time and your own thoughts on this. Let us know of your findings and I am open to any further discussion to make Loki 2.4 usable in Swarm as 2.3 had been until now. Cheers!

**Comment by cassidy3** [comment] 2021-11-26 03:10
Just out of curiosity, is there any reason for Loki to _not_ default to:
```yaml
frontend:
    address: 0.0.0.0
```
Is this just avoided for the sake of network segmentation/security when Loki is deployed as a standalone application (not in a container)? Plenty of other aspects of Loki are configured insecurely by default, so I'm not sure I understand why this one would need to be so strict. For the record, I don't mind the extra config lines; I'm just trying to understand what the Loki devs are going for here in terms of intended deployment. I would think a wide open network config is by far the most versatile for most deployments.

**Comment by KR-Ravindra** [comment] 2021-12-04 05:44
> @tskomudek your solution is working like a charm for me here indeed. Great finding!
> 
> How did you find the `frontend.address` option? It doesn't seem to be documented at all: https://github.com/grafana/loki/blob/main/docs/sources/configuration/_index.md#frontend
> 
> Given that the default configuration in the `loki` Docker image already contains this:
> 
> ```yaml
> common:
>   ring:
>     instance_addr: 127.0.0.1
> ```
> 
> I think what you propose makes sense to use in the default image as well. @owen-d @slim-bean what do you think? Let us know if you need further testing of any kind.

Brilliant, but the ingester never starts. Make sure the ingester is ready over localhost:3100/ready... This should be probably fixed by next release.

**Comment by mvadu** [comment] 2022-01-17 05:23
@trevorwhitney  any chance this can be looked at? latest published image still has this problem in swarm, and we can't run Loki without an external config file like we had in 2.3.

**Comment by trevorwhitney** [comment] 2022-01-18 20:31
Hi @mvadu, sorry, I thought this was resolved using by specifying interface names or addresses manually. Your goal is to run loki in docker swarm without any external config, which worked with Loki 2.3 but does not work in 2.4? I'm guessing that the addition of the query scheduler to the `all` target, or one of the new rings we added, is causing the problem. I'm very curious that there weren't issues with the ingester ring however before this. On 2.3, did you ever have trouble querying recent data from the ingesters?

**Comment by hhromic** [comment] 2022-01-18 22:47
@trevorwhitney yes, I can also confirm that I can't get Loki 2.4.2 working _out of the box_ when deployed in Docker Swarm.

You can refer to my [previous comment](https://github.com/grafana/loki/issues/4699#issuecomment-971526868) (now adapted for Loki 2.4.2) for a minimal Stack file that demonstrates the issue:
```yaml
version: '3.8'

services:
  loki:
    image: grafana/loki:2.4.2
    ports:
      - 3100:3100
    deploy:
      mode: replicated
      replicas: 1
```

The above Stack file can be deployed using this command in a Docker Swarm cluster:

    docker stack deploy -c loki.yaml loki

After the service is up, you can run the following simple query request and never get an OK response from Loki:

    curl -X POST http://localhost:3100/loki/api/v1/query --data 'query={label="value"}'

I also suspect that the default configuration inside the Loki image (in `/etc/loki/local-config.yaml`) probably needs an update to make use of the recently added _interfaces_ configuration.

As a reminder, adding the following snippet does resolve the issue, however we all are looking for an out-of-the-box experience without the need for an external configuration file:
```
frontend:
    address: 0.0.0.0
```

**Comment by trevorwhitney** [comment] 2022-01-20 23:03
@hhromic I was able to re-produce this. Because docker swarm is creating 2 networks (looks like one internal and one for ingress), the node happened to pick up the ingress address (which does not seem accessible from itself), causing the queriers to have trouble communicating with the frontend. A possible solution here is in #5197, which will default the frontend address to `127.0.0.1` in the case of the `all` or `read` targets. However, I need to understand the Frontend -> Scheduler -> Querier -> Frontend flow a little bit better first to make sure this doesn't causes Queriers to be unable to access Frontends on other nodes where a query request may have come in.

**Comment by trevorwhitney** [comment] 2022-01-21 00:13
That PR won't work because as soon as you scale beyond 1 node it will negate the benefits of the scheduler ring. The change that came in 2.4 that is causing this is that queries are now sharded across all instances by default, even in single binary mode (target `all`). In order for this to be possible, queriers (which process the query) need to be able to communicate with query front-ends (which collect all the shards or the query and put the result back together).  When Loki is trying to find the public IP of the front-end, if there is more than one interface, and therefore more than 1 IP (as is the case in the docker swarm example), how is Loki supposed to pick the right one? I'm not sure there's a good way to automatically solve that problem?

That leaves us with a few options here, all which will require external config (either via file or command line args)
* If you're only ever going to run a single instance, hard-coding the frontend address will work
* If you plan to scale, and want to take advantage of query sharding, you'll have to configure the correct network interface for Loki to use.
* If you plan to scale, and don't care about query sharding, you can disable the query-scheduler ring.

I am open to other suggestions on how to solve this problem, but I think the benefits of query sharding are worth keeping on by default, and I just can't think of another way for the front-ends to correctly advertise the address the queriers can reach them at?

**Comment by hhromic** [comment] 2022-01-22 13:20
@trevorwhitney if I understand correctly, the fundamental problem is for Loki needing to know the addresses of other instances in the network when deployed with multiple roles? Note: I am _not_ very familiar with Loki's architecture :(

A common pattern I see in other software that deploys services in a Swarm, is to be able to pass addresses of other instances/services using environment variables or command-line arguments in the Stack files.

Docker in Swarm mode has a `tasks.<service-name>` [internal DNS name](https://docs.docker.com/network/overlay/#container-discovery) that can be used to do this configuration very easily. A very rough pseudo-example of how this could be used:
```yaml
version: '3.8'

services:
  loki-query:
    image: grafana/loki:2.4.2
    environment:
        FRONTEND_ADDRESS: tasks.loki-frontend
    deploy:
      mode: replicated
      replicas: 3
  loki-frontend:
    image: grafana/loki:2.4.2
    environment:
        QUERY_ADDRESS: tasks.loki-query
    ports:
      - 3100:3100
    deploy:
      mode: replicated
      replicas: 1
```

Note that `tasks.<service-name>` actually gives you all the IP addresses of the tasks backing up the service, so DNS lookups will get the addresses of all running replicas in a replicated service.

With an approach like above you shouldn't need for Loki to be bound to specific network interfaces.

Something similar is done by the official Grafana Image Renderer plugin for filling up callback URLs:
https://github.com/grafana/grafana-image-renderer#run-in-docker

**Comment by trevorwhitney** [comment] 2022-01-25 17:39
@hhromic the frontend needs to know it's own address. When it breaks up a query into multiple shards, those shards are picked up by an instance in the pool of query workers. Those workers need to know the specific frontend to send the results back to, since that frontend collecting all the shards to combine back into a single response. The frontend includes an address it can be reached at in the query request. Using a DNS record will not work here if that record is backed by multiple instances, because the process is stateful, those query shards need to respond to the specific frontend where that specific query was initiated.

If docker exposes an an environment variable with a unique address for that specific container, then we could use that. Otherwise, I think the simplest solution here is to specify the list of network interfaces, and exclude the interface listening on the ingress network.

**Comment by hhromic** [comment] 2022-01-25 23:10
@trevorwhitney thanks for the explanation about how Loki works when distributed, it is much clearer to me now :+1:
Luckily, Docker indeed is capable of exposing unique addresses for each contaner (tasks) backing up a Swarm service.

Consider the following example `test` stack:
```yaml
version: '3.8'

services:
  dummy:
    image: alpine
    command: ash -c 'while true; do sleep 1; done'
    hostname: somename
    environment:
      TASK_NAME: '{{ .Task.Name }}'
    ports:
     - 8080:8080
    deploy:
      replicas: 3
```

Note the following about this stack:
* I'm assigning a custom `hostname` to the service to demonstrate that doing so does not matter.
* Important: I'm creating an environment variable and assigning a [template value](https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates).
  * The chosen template is `.Task.Name` which resolves to the unique task name of each container.
* I'm exposing port `8080:8080` for the service to join the ingress network.

After deploying the above stack, you get 3 running tasks/containers backing the `dummy` service defined in it:
```
CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS          PORTS     NAMES
4cbd02073559   alpine:latest   "ash -c 'while true;…"   24 seconds ago   Up 19 seconds             test_dummy.2.ol3tv7dzd43mi22ie853q3589
cd0ef565d070   alpine:latest   "ash -c 'while true;…"   24 seconds ago   Up 20 seconds             test_dummy.1.rked0zm7a59a416rxx2ivrf5j
6ab73f4ab1b7   alpine:latest   "ash -c 'while true;…"   26 seconds ago   Up 20 seconds             test_dummy.3.vxwhvpr5ebg0dyq6xv8n1w00j
```

Now, let's `exec` into one of the containers, for instance task number 2, and inspect its environment:
```
$ docker exec -it test_dummy.2.ol3tv7dzd43mi22ie853q3589 ash
/ # env
HOSTNAME=somename
SHLVL=1
HOME=/root
TASK_NAME=test_dummy.2.ol3tv7dzd43mi22ie853q3589
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```

As you can see, the `TASK_NAME` variable contains the unique task name for this particular container, which also is resolvable via DNS to obtain its particular IP address:
```
/ # nslookup ${TASK_NAME}
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   test_dummy.2.ol3tv7dzd43mi22ie853q3589
Address: 10.0.7.4
```

This address corresponds to the overlay network address, not the ingress network. This can be seen when asking for all the tasks/containers backing up the service:
```
/ # nslookup tasks.dummy
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   tasks.dummy
Address: 10.0.7.3
Name:   tasks.dummy
Address: 10.0.7.4
Name:   tasks.dummy
Address: 10.0.7.5
```

Note: You can get the same result querying the custom `somename` hostname instead of `tasks.dummy`.

Furthermore, this service was deployed with default `endpoint_mode: vip`, which means the service also gets a virtual IP assigned to it in the overlay network:
```
/ # nslookup dummy
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   dummy
Address: 10.0.7.2
```

Lastly, note that every container in the overlay network can talk to any other via their respective Task Name:
```
/ # ping -c2 test_dummy.1.rked0zm7a59a416rxx2ivrf5j
PING test_dummy.1.rked0zm7a59a416rxx2ivrf5j (10.0.7.3): 56 data bytes
64 bytes from 10.0.7.3: seq=0 ttl=64 time=0.196 ms
64 bytes from 10.0.7.3: seq=1 ttl=64 time=0.228 ms

--- test_dummy.1.rked0zm7a59a416rxx2ivrf5j ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.196/0.212/0.228 ms

/ # ping -c2 test_dummy.3.vxwhvpr5ebg0dyq6xv8n1w00j
PING test_dummy.3.vxwhvpr5ebg0dyq6xv8n1w00j (10.0.7.5): 56 data bytes
64 bytes from 10.0.7.5: seq=0 ttl=64 time=0.097 ms
64 bytes from 10.0.7.5: seq=1 ttl=64 time=0.230 ms

--- test_dummy.3.vxwhvpr5ebg0dyq6xv8n1w00j ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.097/0.163/0.230 ms
```

Therefore, if each frontend advertises its own `TASK_NAME` address, then the queriers can get back to them directly.

I believe that explictly passing an environment variable with the unique hostname for each container is far more robust and reliable than trying to guess which interfaces to use on each scenario, specially without user configuration.

**Comment by hhromic** [comment] 2022-01-25 23:25
Note that for users that do NOT set a custom `hostname` in their service definitions, then the container hostname gets automatically assigned from the container ID which is also unique for each task:
```
$ docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS     NAMES
230811e67b43   alpine:latest   "ash -c 'while true;…"   7 seconds ago   Up 1 second              test_dummy.3.sd1je4e9ywozr2rfx68pf9ozc
b148516343a7   alpine:latest   "ash -c 'while true;…"   7 seconds ago   Up 1 second              test_dummy.2.zhj2k2ja6t80h3vtboafg11ae
6bfbaaab3a60   alpine:latest   "ash -c 'while true;…"   8 seconds ago   Up 4 seconds             test_dummy.1.ysl54stg6s8l6y2xwibeum33t

$ docker exec -it test_dummy.2.zhj2k2ja6t80h3vtboafg11ae ash
/ # cat /etc/hostname
b148516343a7

/ # ping -c2 230811e67b43
PING 230811e67b43 (10.0.8.5): 56 data bytes
64 bytes from 10.0.8.5: seq=0 ttl=64 time=0.203 ms
64 bytes from 10.0.8.5: seq=1 ttl=64 time=0.396 ms

--- 230811e67b43 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.203/0.299/0.396 ms

/ # ping -c2 6bfbaaab3a60
PING 6bfbaaab3a60 (10.0.8.3): 56 data bytes
64 bytes from 10.0.8.3: seq=0 ttl=64 time=0.101 ms
64 bytes from 10.0.8.3: seq=1 ttl=64 time=0.228 ms

--- 6bfbaaab3a60 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.101/0.164/0.228 ms
```

In other words, Loki frontends could just pick up the curent hostname of the container and advertise that to the query workers to call back with the results when users do not set set custom hostnames (which is a good practice in general anyway).

**Comment by trevorwhitney** [comment] 2022-01-31 21:16
@hhromic did setting `-frontend.instance-addr` to the unique `TASK_NAME` for each query front-end solve the issue? Alternatively you could use this env var in the config file as long as you set `-config.expand-env`.

**Comment by hhromic** [comment] 2022-01-31 22:54
@trevorwhitney thanks for the suggestion.
I tried it now and it seems to work at least for the single instance case.

I used the following Stack file to test (note that I had to invoke Loki via the shell so the variable gets expanded):
```yaml
version: '3.8'

services:
  loki:
    image: grafana/loki:2.4.2
    entrypoint: /bin/ash
    command:
      -c '/usr/bin/loki -config.file=/etc/loki/local-config.yaml -frontend.instance-addr="$$TASK_NAME"'
    environment:
      TASK_NAME: '{{ .Task.Name }}'
    ports:
      - 3100:3100
    deploy:
      mode: replicated
      replicas: 1
```
Then, querying the Loki service works as expected instead of just hanging:
```
$ curl -G -s http://localhost:3100/loki/api/v1/query --data-urlencode 'query={label="value"}'
{"status":"success","data":{"resultType":"streams","result":[],"stats":{"summary":{"bytesProcessedPerSecond":0,"linesProcessedPerSecond":0,"totalBytesProcessed":0,"totalLinesProcessed":0,"execTime":0.0017295},"store":{"totalChunksRef":0,"totalChunksDownloaded":0,"chunksDownloadTime":0,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":0,"decompressedLines":0,"compressedBytes":0,"totalDuplicates":0},"ingester":{"totalReached":1,"totalChunksMatched":0,"totalBatches":0,"totalLinesSent":0,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":0,"decompressedLines":0,"compressedBytes":0,"totalDuplicates":0}}}}
```

I can't use `-config.expand-env` because that would involve providing a configuration file to the container which is not the idea. Let's remember that the point is that the Loki image works out of the box.

Note: I don't know how to deploy Loki in a multi-frontend configuration, but if you point me on how ot test that, I can help you confirm passing the Task name helps. I'm pretty confident it shoud.

I hope this information helps you find a suitable solution for this problem.
Perhaps the default Loki configuration in the Docker image could contain something like this:
```yaml
frontend:
    address: ${LOKI_FRONTEND_ADDRESS:-}
```
and the default image command is expanded to include the `-config.expand-env` option, therefore users can optionally pass `{{ .Task.Name }}` into said variable name if needed? Just an idea.

**Comment by trevorwhitney** [comment] 2022-02-01 20:17
@hhromic glad that fixed it for you. If you did want to try to setup multiple instances, you could try increasing your `replicas`, and adding a [memberlist configuration](https://grafana.com/docs/loki/latest/configuration/#memberlist_config), so `-memberlist.join` with a DNS record that resolves all your instances.

I'm going to close this issue. I don't know if there's a strong enough case to change defaults at this moment since the current defaults do work out of the box for `docker run`, and any more sophisticated case we're expecting users to provide a config file. However, this is a good data point, and if this issue comes up more then we can investigate a better solution.

**Closed by trevorwhitney** 2022-02-01 20:17 UTC
Labels: kind/bug

**Comment by hhromic** [comment] 2022-02-02 11:57
@trevorwhitney in hopes of making a less ugly Stack file, I'm trying to use the `-frontend.instance-interface-names=lo` command-line argument to tell Loki what interface to use for looking up the address. In this case, to only use the local loopback interface because is a single instance deployment instead of the default `eth0 en0 lo` setting.

However, I noticed that said argument actually _appends_ the interface name to the existing default list instead of _setting_ it alone from the value given in the CLI. For example:

```
$ docker run --rm grafana/loki:2.4.2 -config.file=/etc/loki/local-config.yaml -frontend.instance-interface-names=myiface -print-config-stderr
(...)
frontend:
  log_queries_longer_than: 0s
  max_body_size: 10485760
  query_stats_enabled: false
  max_outstanding_per_tenant: 100
  querier_forget_delay: 0s
  scheduler_address: ""
  scheduler_dns_lookup_period: 10s
  scheduler_worker_concurrency: 5
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 16777216
    grpc_compression: ""
    rate_limit: 0
    rate_limit_burst: 0
    backoff_on_ratelimits: false
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 10
    tls_enabled: false
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_server_name: ""
    tls_insecure_skip_verify: false
  instance_interface_names:   # this should be a list with 'myiface' alone, but 'myiface' got appended instead
  - eth0
  - en0
  - lo
  - myiface
  address: ""
  port: 0
  compress_responses: false
  downstream_url: ""
  tail_proxy_url: ""
(...)
```

Is this a bug that should be reported in a separate issue? Or I'm using the CLI incorrectly here? I noticed that it happens with any CLI argument that refers to interface names. Maybe it affects all options that are lists?

If this is the intended behaviour for `-frontend.instance-interface-names` then the CLI argument is a bit useless because interface names are tried in top-down order in the list :(

For the moment (and for any other readers here), the original problem can be fixed more elegantly for the use case of a **single instance deployment** in Swarm using the `-frontend.instance-addr=127.0.0.1` argument and no need for env variables:
```yaml
version: '3.8'

services:
  loki:
    image: grafana/loki:2.4.2
    command: >-
       -config.file=/etc/loki/local-config.yaml
       -frontend.instance-addr=127.0.0.1
    ports:
      - 3100:3100
    deploy:
      mode: replicated
      replicas: 1
```

**Comment by LinTechSo** [comment] 2022-07-12 13:28
Hi. any updates ?

**Comment by joaoguilhermeS** [comment] 2024-02-14 13:54
> Wow, this one gave me some headache. Finally got it working in Docker Swarm Mode by adding:
> 
> ```
> frontend:
>     address: 127.0.0.1
> ```
> 
> to the config file.

Thank you so much sir! This helped me a lot

**Comment by schenklklopfer** [comment] 2025-06-03 12:08
> > Wow, this one gave me some headache. Finally got it working in Docker Swarm Mode by adding:
> > ```
> > frontend:
> >     address: 127.0.0.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the config file.
> 
> Thank you so much sir! This helped me a lot

Thank you very much! This still works in 2025!
