### ISSUE TITLE
Loki-Grafana - metadata/pod  list in the search labels

### ISSUE THREAD

**Issue by soum1234** [grafana/loki#408] opened 2019-03-18 08:43 UTC
Issues with querying and displaying logs inside Grafana should be opened in the Grafana repo:

https://github.com/grafana/grafana/issues/new
I have extracted the logs from various microservices into grafana using promtail.
and in Grafana UI , i have added the loki datasource.When i click on explore , i can give the pod name of various applications in my cluster and do a log search but before that i could not see some pods listed in the  UI. only if i manually enter the pod name i can see the logs but i would like to see the pod list prepopulated in the UI so that it will be easy to access logs.

**Comment by daixiang0** [comment] 2019-04-02 11:37
Seems it should be done in Grafana UI. @soum1234 could you address the issue?

**Comment by wauk** [comment] 2019-04-17 11:55
I have experienced the same issue that some of the labels do not show up. I can enter the label in grafana {namespace="jenkins-sandbox"} and it will show up with the logs.

This request :
https://localhost:3100/api/prom/label/namespace/values
Only returned a subsection of the namespaces

Using the helm install version 0.6.2

**Comment by Kuqd** [comment] 2019-06-17 16:13
yes this is a duplicate of #453 we're working on it, Thanks for the report @soum1234

**Closed by Kuqd** 2019-06-17 16:13 UTC
