### ISSUE TITLE
Make log level a label

### ISSUE THREAD

**Issue by davkal** [grafana/loki#114] opened 2018-12-15 01:34 UTC
Making log level a filter allows first class filtering of streams by log level.

(Currently log level filtering is done in the UI, on the set of 1000 returned rows. Would be better to do this in loki so that the returned rows are more relevant.)

**Comment by tomwilkie** [comment] 2018-12-16 17:37
Going to close as a dupe of #88, although not quite the same the solutions are consistent - we want to extract data from the log lines themselve into labels.  A good example is log level.

**Closed by tomwilkie** 2018-12-16 17:37 UTC

**Comment by klausenbusk** [comment] 2020-01-02 19:34
How exactly is the current solution implemented? I assume it is implemented client side and Grafana parse every logline for a log level (warn, info, ...)? But I haven't found the relevant code yet.

**Comment by davkal** [comment] 2020-01-02 20:21
To have the log level as a label, it must be done by the logging agent, e.g., Promtail is doing it via pipelines: https://github.com/grafana/loki/blob/master/docs/clients/promtail/pipelines.md

Grafana cannot create its own set of labels. It does two different, additional things: using the `level` label (if present) as a hint to color the log volume histogram. If it cannot find `level` as a label, it parses each log line like you described. The other thing grafana does is parse log lines into fields, i.e., JSON or logfmt structured logs. Those fields are then shown separately when expanding a single log row in Explore.

**Comment by klausenbusk** [comment] 2020-01-02 21:51
> Grafana cannot create its own set of labels. It does two different, additional things: using the `level` label (if present) as a hint to color the log volume histogram. If it cannot find `level` as a label, it parses each log line like you described. The other thing grafana does is parse log lines into fields, i.e., JSON or logfmt structured logs. Those fields are then shown separately when expanding a single log row in Explore.

Thanks for the explanation :)

For anyone else stumbling on this issue and wondering how it is implemented, the relevant code is here:
https://github.com/grafana/grafana/blob/e1acc772979e4dd8db4fbaeda58b842991c00f99/packages/grafana-data/src/types/logs.ts#L9  
https://github.com/grafana/grafana/blob/e1acc772979e4dd8db4fbaeda58b842991c00f99/public/app/core/logs_model.ts#L298-L300  
https://github.com/grafana/grafana/blob/e1acc772979e4dd8db4fbaeda58b842991c00f99/public/app/core/logs_model.ts#L314-L320  
https://github.com/grafana/grafana/blob/e1acc772979e4dd8db4fbaeda58b842991c00f99/packages/grafana-data/src/utils/logs.ts#L13-L42
