### ISSUE TITLE
v2 branch needs for go mod

### ISSUE THREAD

**Issue by morlay** [grafana/loki#3361] opened 2021-02-20 10:29 UTC
**Is your feature request related to a problem? Please describe.**

since Loki switch to go mod, go get will show errors: 

```bash
$ go get github.com/grafana/loki@v2.1.0
go get: github.com/grafana/loki@v2.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
if someone want to use codes of loki. 
will not get the v2.x.x one

**Describe the solution you'd like**

may consider rename branch `master` to `v2`

and module name with `/v2` suffix.
rename all imports of loki too.

**Describe alternatives you've considered**

**Additional context**

**Comment by optiman** [comment] 2021-02-23 10:49
There was some discussion about this earlier: https://github.com/grafana/loki/issues/2826

**Comment by kavirajk** [comment] 2021-03-05 12:49
Closing this. duplicate of #2826

**Closed by kavirajk** 2021-03-05 12:49 UTC
