### ISSUE TITLE
HTTP path-prefix option results to 404 on 2.4.1

### ISSUE THREAD

**Issue by vooon** [grafana/loki#4756] opened 2021-11-15 15:28 UTC
**Describe the bug**

After update to 2.4.1 i had query errors. During config debugging i tried https://github.com/grafana/loki/issues/4699#issuecomment-963227228 which worked fine until i set server.http_path_prefix="/loki" to match my config.
E.g. `logcli --addr http://localhost:3101/loki query {job=~".+"}` responds with 404.

**To Reproduce**
1. Started Loki (2.4.1)
2. Started promtail
3. Query: `{job=~".+"} term` (note: any query, just i used that one)

**Expected behavior**
Expected to get some lines.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: manual run of `-target=all`

**Screenshots, Promtail config, or terminal output**
```
$ logcli --addr 'http://192.168.50.10:3100/loki' query '{job=~".+"}'
2021-11-15 15:55:57.263288 I | proto: duplicate proto type registered: purgeplan.DeletePlan
2021-11-15 15:55:57.263374 I | proto: duplicate proto type registered: purgeplan.ChunksGroup
2021-11-15 15:55:57.263382 I | proto: duplicate proto type registered: purgeplan.ChunkDetails
2021-11-15 15:55:57.263388 I | proto: duplicate proto type registered: purgeplan.Interval
2021-11-15 15:55:57.280009 I | proto: duplicate proto type registered: grpc.PutChunksRequest
2021-11-15 15:55:57.280041 I | proto: duplicate proto type registered: grpc.GetChunksRequest
2021-11-15 15:55:57.280052 I | proto: duplicate proto type registered: grpc.GetChunksResponse
2021-11-15 15:55:57.280061 I | proto: duplicate proto type registered: grpc.Chunk
2021-11-15 15:55:57.280078 I | proto: duplicate proto type registered: grpc.ChunkID
2021-11-15 15:55:57.280087 I | proto: duplicate proto type registered: grpc.DeleteTableRequest
2021-11-15 15:55:57.280096 I | proto: duplicate proto type registered: grpc.DescribeTableRequest
2021-11-15 15:55:57.280104 I | proto: duplicate proto type registered: grpc.WriteBatch
2021-11-15 15:55:57.280112 I | proto: duplicate proto type registered: grpc.WriteIndexRequest
2021-11-15 15:55:57.280120 I | proto: duplicate proto type registered: grpc.DeleteIndexRequest
2021-11-15 15:55:57.280128 I | proto: duplicate proto type registered: grpc.QueryIndexResponse
2021-11-15 15:55:57.280136 I | proto: duplicate proto type registered: grpc.Row
2021-11-15 15:55:57.280144 I | proto: duplicate proto type registered: grpc.IndexEntry
2021-11-15 15:55:57.280152 I | proto: duplicate proto type registered: grpc.QueryIndexRequest
2021-11-15 15:55:57.280160 I | proto: duplicate proto type registered: grpc.UpdateTableRequest
2021-11-15 15:55:57.280168 I | proto: duplicate proto type registered: grpc.DescribeTableResponse
2021-11-15 15:55:57.280176 I | proto: duplicate proto type registered: grpc.CreateTableRequest
2021-11-15 15:55:57.280184 I | proto: duplicate proto type registered: grpc.TableDesc
2021-11-15 15:55:57.280192 I | proto: duplicate proto type registered: grpc.TableDesc.TagsEntry
2021-11-15 15:55:57.280200 I | proto: duplicate proto type registered: grpc.ListTablesResponse
2021-11-15 15:55:57.280209 I | proto: duplicate proto type registered: grpc.Labels
2021-11-15 15:55:57.280374 I | proto: duplicate proto type registered: storage.Entry
2021-11-15 15:55:57.280390 I | proto: duplicate proto type registered: storage.ReadBatch
http://192.168.50.10:3100/loki/loki/api/v1/query_range?direction=BACKWARD&end=1636980957281844223&limit=30&query=%7Bjob%3D~%22.%2B%22%7D&start=1636977357281844223
Error response from server: 404 page not found
 (<nil>) attempts remaining: 0
Query failed: Run out of attempts while querying the server
```
```
logcli, version 2.4.1 (branch: HEAD, revision: f61a4d261)
  build user:       root@9cbe2f86250f
  build date:       2021-11-08T13:05:10Z
  go version:       go1.16.2
  platform:         linux/amd64
```

**Comment by vooon** [comment] 2021-11-15 15:37
In addition i can't bind grpc on private network anymore, because frontend tries to connect from 127.0.0.1. Log have errors about  and eth0, en0 interfaces, even though i set:
```
common:
  path_prefix: "/var/lib/loki"
  replication_factor: 1  # default is 3
  ring: &common_ring
    instance_addr: "192.168.50.10"
    instance_interface_names: ["vlan2000"]
    ...
```

**Comment by azuregos** [comment] 2021-11-19 10:25
I concur that issue exists with Loki 2.4.1 after `http_path_prefix` is being set.

###  

1. Create Loki configuration file `loki.yaml`
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_path_prefix: /loki

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: true

schema_config:
  configs:
    - from: 2021-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
```
2. Create Docker compose file `docker-compose.yml`
```yaml
version: "3.9"
services:

  loki:
    image: grafana/loki:2.4.1
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki.yaml:/etc/loki/config.yaml:ro
    ports:
      - 3100:3100
    networks:
      - loki

  grafana:
    image: grafana/grafana:8.2.5
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - loki

networks:
  loki:
```
3. Run Docker compose with `docker compose up -d` command
4. Open Grafana UI in a browser (`http://localhost:3000/login`) and log is as `admin/admin`
5. Add Loki datasource using url `http://loki:3100/loki`
6. Open Grafana's `Explore` panel and attempt to query Loki using query `{Job="Foo"}`
7. Note the 404 error reported by Grafana

If `http_path_prefix` is not being specified in `loki.yaml` file the same setup will work flawlessly.

**Comment by azuregos** [comment] 2021-11-19 12:29
Loki **2.4.0**: Issue also present
Loki **2.3.0**: Issue **NOT** present

**Comment by azuregos** [comment] 2022-01-12 09:07
This issue is still very relevant, a serious regression and a blocker for us. 
Without URL path prefix we can't access Loki instance behind a reverse proxy. Not everyone can forward ports so having a control over what URL your APIs have is a must.

**Comment by grzegorznowak** [comment] 2022-01-21 07:57
This thread saved my a lot of grief, thanks guys.
The only thing to add here is I couldn't still make it to connect grafana -> loki based on the suggestions above. Removal of `http_path_prefix` didn't fix the 502 and `curl -G -s  http://10.0.1.190:3100/loki/api/v1/labels` was still hanging.

Our local setup binds both loki and grafana to virtual mesh VPN interface and it does work OK under `2.3.0`, but no go on `2.4.*` so far. Unless we bind everything to public interface of course, then it runs tip-top.

**Comment by vooon** [comment] 2022-01-21 09:23
@grzegorznowak you need to set `instance_addr` and `instance_interface_names` and some other parameters, but i'm actually stuck on trouble with some of services not obeying them. So i gave up and set grpc port to listen on '[::]' and just added iptables rule...
And yes, for 2.3.0 it's been enough to set those two variables in ring...

**Comment by azuregos** [comment] 2022-03-03 22:51
The problem is still very relevant and very critical. No go on using Loki 2.4+ until its fixed for us.

**Comment by azuregos** [comment] 2022-04-14 20:52
In case you were wondering Loki **2.5.0** still has this issue. 😞

**Comment by s-frei** [comment] 2022-04-26 08:25
Stumbled upon the same issue upgrading from *2.2.1* to *2.5.0*. As already mentioned it is not really nice to have it behind a reverse proxy like this... Since I'm not into Go I cannot provide a fix for this, unfortunately.

**Comment by MaximeTaqt** [comment] 2022-06-11 07:57
Same issue too.
I downgraded to 2.3.0

**Comment by gjed** [comment] 2022-06-16 11:22
On a related note: grafana 9.0.0 actively strip the path prefix from loki url (see [#50939](https://github.com/grafana/grafana/issues/50939))

**Comment by v1ctorrhs** [comment] 2022-09-09 07:54
+1 here, we are also facing the same issue, loki 2.6.1

**Comment by QuentinM-Hilbtec** [comment] 2022-11-01 22:14
I had updated to 2.6.1 to get deletion support, but rolled back to 2.3.0 after hitting #6231 which appears directly related to this. Unfortunately had to delete my v12 index as well at the same time.

**Comment by debuglevel** [comment] 2022-12-29 12:05
Just tested Loki on my machine and wondered why it just did not work when I wanted to use it in production. I guess I have to use the over a year old version 2.3.0
o_O

**Comment by ryoshindo** [comment] 2023-02-02 15:31
I have confirmed that this bug has not been fixed in v2.7.2. I would love to have this bug fixed as it is a very serious problem for my use of loki.
Thanks

**Closed** 2023-06-23 20:36 UTC
Labels: component/querier, type/bug

**Comment by tiran133** [comment] 2023-09-20 06:23
Still Happening in v2.9.1 Getting 404 in Grafana.  

https://github.com/grafana/loki/pull/8406#issuecomment-1707376796

**Comment by fsiler** [comment] 2023-09-21 15:19
I have this same issue- manually bisected as described [here](https://github.com/grafana/loki/pull/8406#issuecomment-1707376796).

**Comment by Pexers** [comment] 2024-01-24 13:07
+1
Issue persists in `grafana/loki:2.9.3`. Like others said, when the prefix path is not specified, everything works just fine.. 😞

**Comment by pciavald** [comment] 2024-10-31 11:16
had the same issue, downgraded to 2.3.0 but there was too many config issues, upgraded to 3.2.1 and it seems to work
