### ISSUE TITLE
We should document how to do alerting with Loki/Promtail

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1753] opened 2020-02-27 13:47 UTC
**Is your feature request related to a problem? Please describe.**

We plan to do ruling and alerting like Prom with Alertmanager, but in the meantime we have multiple ways to already alerts on logs and I think we should document it.

This include alerting with Promtail/Alertmanager using stages or alerting with Grafana using Loki as Prometheus datasource.

We should also explain that you can use filter in the match selector stage:

```
pipeline_stages:
      - match:
          selector: '{app="promtail"} |= "panic"'
      - metrics:
          panic_total:
            type: Counter
            description: "total number of panic"
            config:
              match_all: true
              action: inc
```

**Comment by wardbekker** [comment] 2020-02-28 11:06
Video that illustrates the Grafana/Loki/Prometheus combo: https://www.youtube.com/watch?v=GdgX46KwKqo

**Comment by davidelavarga** [comment] 2020-03-11 15:28
Hello,

I follow video instructions:

![image](https://user-images.githubusercontent.com/37444330/76431829-6c44d400-63b2-11ea-96dc-7e837320397d.png)

 **Query:** 
`count_over_time( ( {namespace="dev-v1"} |= "[E]" )[1m] )`  (Spacers included)

**Alert:**
![image](https://user-images.githubusercontent.com/37444330/76432062-baf26e00-63b2-11ea-824b-95527b288e39.png)

If I select "if execution error or timeout" as Alerting, I have this error in the alert: 
`lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=1 name="Log Errors alert" error="tsdb.HandleRequest() error bad_response: invalid character 'r ' looking for beginning of value" changing state to=alerting`

But if I choose "Keep Last State", this error is omitted. However, there are not alerts and I have values below "3".

But I don't know why the alerts doesn't throw itself.

I have installed loki-stack using helm chart (grafana:6.4.1, loki:v1.0.0)

**Comment by cyriltovena** [comment] 2020-03-11 19:52
Do you mind trying Loki v1.3.0 ?

**Comment by davidelavarga** [comment] 2020-03-12 09:45
Thank you a lot. With loki 1.3.0 works fine

**Comment by cyriltovena** [comment] 2020-03-12 10:42
Yeah I think we did 1.1/1.2 because of a small API drift, You might have been affected by that.

**Comment by jazoom** [comment] 2020-03-13 05:00
> Video that illustrates the Grafana/Loki/Prometheus combo: https://www.youtube.com/watch?v=GdgX46KwKqo

Thanks for the video. That would have been very difficult to figure out without it. I think I'm still missing something, though. I've gotten to the point where I receive an email every time the string `***ALERT***` is present in a log. I know it's working because I get these emails at exactly the same time as my current logging solution. The problem is, there is "No Data" in the emails, nor in the Alerts List on the Grafana dashboard.

For this to be a useful logging solution these emails really need to contain the matched log lines that triggered the alert within the specified time period (last 5 minutes, for example). At the moment those emails show nothing other than an alert exists.

Is there a way to show the actual logs in the email? I assume fixing this will also fix the items in the Alert List.

**Comment by cyriltovena** [comment] 2020-03-16 21:21
You could use a log panel with the same query without the rate/count_over_time in your dashboard.

This is a workaround, the real answer is, we're planning to support prometheus alert/rule style. Not sure if this will contains the actual log line but this is good feedback for #340 .

**Comment by MalloZup** [comment] 2020-05-26 08:51
any update on this?

**Comment by cyriltovena** [comment] 2020-05-27 17:28
@owen-d is focusing on this, we're aiming for this quarter.

**Comment by JnMik** [comment] 2020-06-04 02:14
I create a dashboard over a "Prometheus Loki" datasource as I found on the internet.
My queries to lookup for keywords looks like that for example : 

```
sum(count_over_time({container_name!="loki"} |~ "Unexpected error occurred"[$__interval])) by (container_name)
```

But when I set an Alert on top of this dashboard, nothing happens even if I bust the threshold. 
If I click "test rule" I receive this 

```
firing:true
error:"tsdb.HandleRequest() error bad_response: readObjectStart: expect { or n, but found p, error found in #1 byte of ...|parse error|..., bigger context ...|parse error at line 0, col 70: not a valid duration|..."
```

Any idea what I might have done wrong ?

**Comment by JnMik** [comment] 2020-06-04 15:57
Oh I found this ! https://github.com/grafana/loki/issues/2117
My reference to $__interval was faulty

**Comment by IamEnTm** [comment] 2020-06-07 16:58
> > Video that illustrates the Grafana/Loki/Prometheus combo: https://www.youtube.com/watch?v=GdgX46KwKqo
> 
> Thanks for the video. That would have been very difficult to figure out without it. I think I'm still missing something, though. I've gotten to the point where I receive an email every time the string `***ALERT***` is present in a log. I know it's working because I get these emails at exactly the same time as my current logging solution. The problem is, there is "No Data" in the emails, nor in the Alerts List on the Grafana dashboard.
> 
> For this to be a useful logging solution these emails really need to contain the matched log lines that triggered the alert within the specified time period (last 5 minutes, for example). At the moment those emails show nothing other than an alert exists.
> 
> Is there a way to show the actual logs in the email? I assume fixing this will also fix the items in the Alert List.

Hey!
Can you please explain how you managed to receive an email for each '***ALERT***'?
All I can do is get one alert and then have to wait until it's "resolved" in order to get a new one.

**Comment by slim-bean** [comment] 2020-09-17 13:15
Closing this as sort of a duplicate of #340, but also because recently alerting directly to an alert manager was merged into Loki.

**Closed by slim-bean** 2020-09-17 13:15 UTC
Labels: component/docs, good first issue, help wanted, keepalive

**Comment by MalloZup** [comment] 2020-09-19 12:25
@slim-bean  cool to hear that! is there any docs avail for the end user ? tia

**Comment by owen-d** [comment] 2020-09-19 13:35
The docs will PR is on the way: https://github.com/grafana/loki/pull/2637

**Comment by lgg42** [comment] 2020-10-12 22:55
So, is it possible now to send the actual log lines that triggered the alert in the alert message? (Email, slack, whatever..)
Is the only thing I'm missing in Loki. Everything else is damn great.

Say, if Loki notifies Alert manager of high 5xx error rate in the last 5min I'd like not only to get notified on the metric condition (instant vector) (which already works) but also have the log lines that triggered such alert.

**Comment by geokat** [comment] 2020-10-12 23:13
Or, even better, the log line and its URL in Grafana :)

That would be a killer feature!

**Comment by saada** [comment] 2021-12-28 05:05
Getting loglines and a Grafana url would be fantastic

**Comment by postol** [comment] 2022-01-14 12:44
We are also missing the feature where loglines can be sent as part of an alert. Is there any way how to do this or ETA when this would be available?

**Comment by mihma** [comment] 2022-07-31 17:22
Also can't wait for this feature
