### ISSUE TITLE
Log location incorrect (for GKE 1.12.6+)

### ISSUE THREAD

**Issue by Robert-Stam** [grafana/loki#487] opened 2019-04-16 09:49 UTC
**Describe the bug**
The log file location promtail is looking for in the provided sample config doesn't work as of Kubernetes 1.12.6 (where the location is changed)

**To Reproduce**
1. Started loki (master-63be9c2)
2. Started promtail (master-63be9c2)
3. Started Grafana (v6.1.3)
  a) on the Explore tab select Loki
   - this will result in the message that no labels has been received

**Expected behavior**
Log files will be scraped

**Environment:**
 - Infrastructure: Kubernetes Google Cloud v1.12.6-gke.10
 - Deployment tool: [yaml - kustomize - kubectl (apply)]

**Screenshots, promtail config, or terminal output**
original promtail config (relevant snippet)

     `- replacement: /var/log/pods/$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__`
modified promtail config (which solved this issue, however will not work on previous kubernetes versions)

      `- action: replace
        separator: _
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
        - __meta_kubernetes_pod_uid
        target_label: __tmp_log_folder #__tmp prefix is reserved for this and automatically dropped
      - replacement: /var/log/pods/$1/*.log
        separator: /
        source_labels:
        - __tmp_log_folder
        - __meta_kubernetes_pod_container_name
        target_label: __path__`

Hope this helps

**Comment by daixiang0** [comment] 2019-04-16 13:10
you can say `job_name` in sd_config, which mean you can enter more job as you want, so, you can add a new job for 1.12.

**Comment by steven-sheehy** [comment] 2019-04-16 16:27
This looks to be a duplicate of https://github.com/grafana/loki/issues/393. Even though you're not on 1.14, what you're showing as working is the new log directory format.

**Comment by daixiang0** [comment] 2019-04-18 01:40
@Robert-Stam  hi, please update scrape_config and try, wait for your update.

**Comment by Robert-Stam** [comment] 2019-04-18 06:25
Hi, Currently we are using 1.12.6+ on all platforms, so my edit (see above) is OK for US.
I just wanted to let you (are others) know that the new folder format has been introduced earlier than 1.14.0 (maybe you can update the diagnostics page with this info). 
On the diagnostics page the current new format contains a lot of wildcards (in my sample I used the more strict new format). Hope this help. 

We can close this issue if you want, so need for me to keep it open.

**Closed** 2019-04-18 12:35 UTC
